    <section class="ui-panel ui-section">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-semibold  text-slate-500 text-base sm:text-sm">Manual control</p><h2 class="mt-1 text-lg font-semibold">Outreach lifecycle</h2><p class="mt-1 text-slate-500 text-base sm:text-sm">{{ str($prospect->outreachState->lifecycle_state->value)->replace('_', ' ')->title() }} · Automation {{ $prospect->outreachState->automation_status->value }} · Score {{ $prospect->outreachState->engagement_score }}</p></div></div>
        <div class="mt-4 grid gap-3 md:grid-cols-2">
            @foreach ([
                ['pause', 'Pause automation', 'Temporarily prevents scheduled sequence actions while keeping the prospect’s place.'],
                ['resume', 'Resume automation', 'Restarts due sequence actions for a prospect that is not in a stopped lifecycle state.'],
                ['force_warm', 'Force Warm', 'Manually classifies this prospect as warm regardless of their current engagement score.'],
                ['force_hot', 'Force Hot', 'Moves the prospect into the personalised-video queue and pauses cold follow-ups.'],
                ['clear_temperature_override', 'Use automatic score', 'Removes the manual Warm or Hot override and calculates temperature from the engagement score.'],
            ] as [$action, $label, $description])
                <form method="POST" action="{{ route('admin.prospects.lifecycle', $prospect) }}" class="flex flex-col items-start gap-2 border-b border-slate-950/10 py-4">@csrf @method('PATCH')<input type="hidden" name="action" value="{{ $action }}"><button type="submit" class="ui-button relative ui-button-secondary">{{ $label }}<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button><p class="text-base/6 text-slate-500 sm:text-sm/5">{{ $description }}</p></form>
            @endforeach
            @foreach ([
                ['stop', 'Stop outreach', 'Stops all normal automated outreach without changing the prospect’s sales outcome.'],
                ['mark_replied', 'Mark replied', 'Records a reply, cancels future automated messages, and moves the prospect to manual handling.'],
                ['mark_not_interested', 'Not interested', 'Records that the prospect declined and permanently stops the normal outreach sequence.'],
                ['mark_customer', 'Customer', 'Marks the prospect as converted into a customer and stops all prospecting emails.'],
                ['mark_pilot', 'Pilot', 'Marks the prospect as an active pilot and stops all prospecting emails.'],
            ] as [$action, $label, $description])
                <form method="POST" action="{{ route('admin.prospects.lifecycle', $prospect) }}" data-confirm-action-form class="flex flex-col items-start gap-2 border-b border-slate-950/10 py-4">@csrf @method('PATCH')<input type="hidden" name="action" value="{{ $action }}"><button type="button" data-confirm-action data-confirm-title="{{ $label }}?" data-confirm-message="This action stops the normal automated outreach sequence." data-confirm-label="{{ $label }}" class="ui-button relative ui-button-secondary">{{ $label }}<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button><p class="text-base/6 text-slate-500 sm:text-sm/5">{{ $description }}</p></form>
            @endforeach
        </div>
        <div class="mt-5 border-t border-slate-950/10 pt-5"><h3 class="text-sm font-semibold text-slate-900">Dates and engagement score</h3><p class="mt-1 text-slate-500 text-base sm:text-sm">Use these tools when a prospect should be revisited later or their automated engagement score needs a manual correction.</p></div>
        <div class="mt-4 grid gap-4 lg:grid-cols-2">
            <form method="POST" action="{{ route('admin.prospects.lifecycle', $prospect) }}" class="ui-well p-4">@csrf @method('PATCH')<input type="hidden" name="action" value="mark_future_opportunity"><div><label for="future_opportunity_at" class="ui-label text-slate-900">Contact later <span class="font-normal text-slate-500">(UK time)</span></label><p class="mt-1 leading-6 text-slate-600 text-base sm:text-sm">Stops the current sequence and stores a date for this prospect to return as a future opportunity. It will not automatically restart outreach.</p><input id="future_opportunity_at" type="datetime-local" name="future_opportunity_at" required min="{{ now('Europe/London')->addMinute()->format('Y-m-d\TH:i') }}" class="ui-input mt-3 w-full"></div><button type="submit" class="ui-button relative ui-button-secondary mt-3">Mark future opportunity<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button></form>
            <div class="ui-well p-4"><form method="POST" action="{{ route('admin.prospects.lifecycle', $prospect) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="adjust_score"><p class="font-semibold text-slate-900 text-base sm:text-sm">Adjust engagement score</p><p class="mt-1 leading-6 text-slate-500 text-base sm:text-sm">Add or subtract points to correct the automated score. Enter the amount under Score ± and record why under Reason; the change remains in the activity history.</p><div class="mt-3 grid gap-2 sm:grid-cols-[6rem_1fr_auto] sm:items-end"><div><label for="score_delta" class="ui-label">Score ±</label><input id="score_delta" type="number" name="score_delta" min="-100" max="100" required class="ui-input mt-1 w-full"></div><div><label for="score_reason" class="ui-label">Reason</label><input id="score_reason" name="reason" required class="ui-input mt-1 w-full"></div><button type="submit" class="ui-button relative ui-button-secondary">Adjust<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button></div></form><form method="POST" action="{{ route('admin.prospects.lifecycle', $prospect) }}" data-confirm-action-form class="mt-4 border-t border-slate-950/10 pt-3">@csrf @method('PATCH')<input type="hidden" name="action" value="reset_score"><input type="hidden" name="reason" value="Score reset manually"><button type="button" data-confirm-action data-confirm-title="Reset engagement score?" data-confirm-message="The current score will return to zero. The immutable engagement history remains available." data-confirm-label="Reset score" class="text-sm font-semibold text-red-700 hover:underline">Reset engagement score<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button><p class="mt-1 leading-6 text-slate-500 text-base sm:text-sm">Returns the score to zero without deleting the prospect’s engagement events or activity history.</p></form></div>
        </div>
    </section>
