                <section id="personalised-video" class="ui-panel ui-section scroll-mt-6">
                    <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-medium text-teal-700 text-base sm:text-sm">Hot lead · manual action</p><h2 class="mt-1 text-lg font-semibold text-slate-950">Add / Send Personalised Video</h2><p class="mt-1 text-slate-600 text-base sm:text-sm">Save and test this separate video email before sending. Cold follow-ups are paused; no automatic email follows this video.</p></div><span class="rounded-md bg-teal-50 px-2 py-1 font-medium text-teal-800">Score {{ $prospect->outreachState->engagement_score }}</span></div>
                    @if ($scheduledVideoDelivery)
                        <p class="mt-4 rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-slate-600 text-base sm:text-sm">Scheduled for {{ $scheduledVideoDelivery->scheduled_at->setTimezone('Europe/London')->format('j M Y, H:i') }} UK time. Saving a draft or sending yourself a test leaves this scheduled email unchanged. Schedule video replaces it; Send video now sends immediately.</p>
                    @endif
                    <form method="POST" action="{{ route('admin.prospects.personalised-video', $prospect) }}" class="mt-4 space-y-4">
                        @csrf
                        <div><label for="video_url" class="ui-label">Personalised video URL</label><input id="video_url" type="url" name="video_url" required value="{{ old('video_url', $prospect->outreachState->personalised_video_draft['video_url'] ?? $prospect->showcase_video_url) }}" placeholder="https://www.loom.com/share/..." class="ui-input mt-1 w-full"></div>
                        <div><label for="video_subject" class="ui-label">Subject</label><input id="video_subject" name="subject" required value="{{ old('subject', $prospect->outreachState->personalised_video_draft['subject'] ?? $scheduledVideoDelivery?->subject ?? $personalisedVideoSubject) }}" class="ui-input mt-1 w-full"></div>
                        <div><label for="video_body" class="ui-label">Message</label><textarea id="video_body" name="body" rows="8" required class="ui-input mt-1 w-full">{{ old('body', $prospect->outreachState->personalised_video_draft['body'] ?? $scheduledVideoDelivery?->body ?? $personalisedVideoBody) }}</textarea></div>
                        <div class="flex flex-wrap gap-2">
                            <button type="submit" name="action" value="save_draft" class="ui-button relative ui-button-primary">Save video draft<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button>
                            <button type="submit" name="action" value="send_test" class="ui-button relative ui-button-secondary">Save &amp; send me a test<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button>
                        </div>
                        <p class="text-base text-slate-600 sm:text-sm">The test goes to {{ auth()->user()->email }} using the message above. Test opens and clicks do not count as lead engagement.</p>
                        <div class="flex flex-col gap-3 ui-well p-4 sm:flex-row sm:items-end">
                            <div class="min-w-0 flex-1"><label for="video_scheduled_send_at" class="ui-label">Schedule time <span class="font-normal text-slate-500">(optional, UK time)</span></label><input id="video_scheduled_send_at" type="datetime-local" name="scheduled_send_at" value="{{ old('scheduled_send_at', $scheduledVideoDelivery?->scheduled_at?->setTimezone('Europe/London')->format('Y-m-d\TH:i')) }}" class="ui-input mt-1 w-full"></div>
                            <div class="flex flex-wrap gap-2"><button type="submit" name="action" value="schedule" class="ui-button relative ui-button-secondary">Schedule video<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button><button type="submit" name="action" value="send_now" class="ui-button relative ui-button-secondary">Send video now<span class="absolute top-1/2 left-1/2 size-[max(100%,3rem)] -translate-1/2 pointer-fine:hidden" aria-hidden="true"></span></button></div>
                        </div>
                    </form>
                </section>
