<?php

namespace App\Services;

use App\Models\GithubInstallation;
use App\Models\GithubUserAuthorization;
use App\Models\User;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use RuntimeException;

class GithubOAuthClient
{
    public function refreshInstallation(
        GithubUserAuthorization $authorization,
        GithubInstallation $installation,
    ): GithubInstallation {
        $page = 1;
        $details = null;

        do {
            $installations = $this->apiRequest($this->accessToken($authorization))
                ->get('user/installations', ['per_page' => 100, 'page' => $page])
                ->throw()
                ->json('installations', []);
            $details = collect($installations)->firstWhere('id', $installation->installation_id);
            $page++;
        } while (! is_array($details) && count($installations) === 100);

        if (! is_array($details)) {
            throw new RuntimeException('Your GitHub account can no longer access this Sitewell installation. Reconnect GitHub and try again.');
        }

        $installation->update([
            'account_id' => $details['account']['id'],
            'account_login' => $details['account']['login'],
            'account_type' => $details['account']['type'],
            'repository_selection' => $details['repository_selection'],
            'permissions' => $details['permissions'] ?? [],
            'status' => isset($details['suspended_at']) && $details['suspended_at'] !== null
                ? GithubInstallation::STATUS_SUSPENDED
                : GithubInstallation::STATUS_ACTIVE,
            'suspended_at' => $details['suspended_at'] ?? null,
        ]);

        return $installation->refresh();
    }

    /** @param array<string, string> $files
     * @return array<string, mixed>
     */
    public function createRepository(
        GithubUserAuthorization $authorization,
        string $owner,
        string $name,
        array $files,
    ): array {
        $token = $this->accessToken($authorization);
        $endpoint = $owner === $authorization->github_login ? 'user/repos' : "orgs/{$owner}/repos";
        $response = $this->apiRequest($token)->post($endpoint, [
            'name' => $name,
            'description' => 'Website generated by Sitewell.',
            'private' => false,
        ]);

        if ($response->forbidden()) {
            throw new RuntimeException('GitHub refused repository creation. Confirm the Sitewell GitHub App has Repository permissions → Administration set to Read and write, the updated permission has been approved for the installation, and the organisation allows GitHub Apps to create repositories.');
        }

        $repository = $response->throw()->json();

        if (! is_string($repository['full_name'] ?? null)) {
            throw new RuntimeException('GitHub did not return the new repository details.');
        }

        foreach ($files as $path => $contents) {
            $this->apiRequest($token)
                ->put("repos/{$repository['full_name']}/contents/{$path}", [
                    'message' => 'Build initial website',
                    'content' => base64_encode($contents),
                ])
                ->throw();
        }

        return $repository;
    }

    public function authorizationUrl(string $state): string
    {
        $this->ensureConfigured();

        return (string) config('services.github.oauth_url').'/authorize?'.http_build_query([
            'client_id' => config('services.github.client_id'),
            'redirect_uri' => route('admin.github.callback'),
            'state' => $state,
        ]);
    }

    public function authorize(User $user, string $code): GithubUserAuthorization
    {
        $tokens = $this->tokenRequest([
            'client_id' => config('services.github.client_id'),
            'client_secret' => config('services.github.client_secret'),
            'code' => $code,
            'redirect_uri' => route('admin.github.callback'),
        ]);
        $githubUser = $this->apiRequest($tokens['access_token'])->get('user')->throw()->json();

        return GithubUserAuthorization::query()->updateOrCreate(
            ['user_id' => $user->id],
            $this->authorizationAttributes($tokens, $githubUser),
        );
    }

    public function accessToken(GithubUserAuthorization $authorization): string
    {
        if (! $authorization->access_token_expires_at || $authorization->access_token_expires_at->isAfter(now()->addMinutes(5))) {
            return $authorization->access_token;
        }

        return Cache::lock('github-oauth-refresh-'.$authorization->id, 20)->block(5, function () use ($authorization): string {
            $authorization->refresh();

            if ($authorization->access_token_expires_at?->isAfter(now()->addMinutes(5))) {
                return $authorization->access_token;
            }

            if (! $authorization->refresh_token || $authorization->refresh_token_expires_at?->isPast()) {
                throw new RuntimeException('The GitHub authorization has expired. Reconnect GitHub to continue.');
            }

            $tokens = $this->tokenRequest([
                'client_id' => config('services.github.client_id'),
                'client_secret' => config('services.github.client_secret'),
                'grant_type' => 'refresh_token',
                'refresh_token' => $authorization->refresh_token,
            ]);

            $authorization->update($this->tokenAttributes($tokens));

            return $authorization->fresh()->access_token;
        });
    }

    public function canAccessInstallation(GithubUserAuthorization $authorization, int $installationId): bool
    {
        $page = 1;

        do {
            $installations = $this->apiRequest($this->accessToken($authorization))
                ->get('user/installations', ['per_page' => 100, 'page' => $page])
                ->throw()
                ->json('installations', []);

            if (collect($installations)->contains('id', $installationId)) {
                return true;
            }

            $page++;
        } while (count($installations) === 100);

        return false;
    }

    /** @param array<string, mixed> $parameters
     * @return array<string, mixed>
     */
    protected function tokenRequest(array $parameters): array
    {
        $this->ensureConfigured();

        $tokens = Http::acceptJson()
            ->asForm()
            ->connectTimeout(5)
            ->timeout(15)
            ->post((string) config('services.github.oauth_url').'/access_token', $parameters)
            ->throw()
            ->json();

        if (! is_array($tokens) || ! is_string($tokens['access_token'] ?? null)) {
            throw new RuntimeException('GitHub did not return a user access token.');
        }

        return $tokens;
    }

    protected function apiRequest(string $token): PendingRequest
    {
        return Http::baseUrl((string) config('services.github.api_url'))
            ->acceptJson()
            ->withHeaders([
                'X-GitHub-Api-Version' => '2026-03-10',
                'User-Agent' => config('app.name').' GitHub App',
            ])
            ->withToken($token)
            ->connectTimeout(5)
            ->timeout(15);
    }

    /** @param array<string, mixed> $tokens
     * @param  array<string, mixed>  $githubUser
     * @return array<string, mixed>
     */
    protected function authorizationAttributes(array $tokens, array $githubUser): array
    {
        return [
            'github_user_id' => $githubUser['id'],
            'github_login' => $githubUser['login'],
            ...$this->tokenAttributes($tokens),
        ];
    }

    /** @param array<string, mixed> $tokens
     * @return array<string, mixed>
     */
    protected function tokenAttributes(array $tokens): array
    {
        return [
            'access_token' => $tokens['access_token'],
            'access_token_expires_at' => isset($tokens['expires_in']) ? now()->addSeconds((int) $tokens['expires_in']) : null,
            'refresh_token' => $tokens['refresh_token'] ?? null,
            'refresh_token_expires_at' => isset($tokens['refresh_token_expires_in']) ? now()->addSeconds((int) $tokens['refresh_token_expires_in']) : null,
        ];
    }

    protected function ensureConfigured(): void
    {
        if (! config('services.github.client_id') || ! config('services.github.client_secret')) {
            throw new RuntimeException('GitHub OAuth is not configured.');
        }
    }
}
