@extends('layouts.app')
@section('content')
<div class="space-y-6">
    <header><a href="{{ route('admin.ai-visibility.index', $website) }}" class="text-sm font-medium text-teal-700">← AI Visibility</a><h1 class="mt-3 max-w-4xl text-2xl font-semibold text-slate-950">{{ $prompt->prompt }}</h1><p class="mt-2 text-sm text-slate-500">{{ $prompt->trashed() ? 'Deleted · historical evidence retained' : ($prompt->active ? 'Tracking' : 'Disabled') }} · {{ ucfirst($prompt->priority) }} priority</p></header>
    @if ($errors->any())<div role="alert" class="rounded-xl bg-red-50 p-4 text-sm text-red-800">@foreach ($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold text-slate-950">Latest results</h2><div class="mt-4 flex flex-wrap gap-6">@forelse ($latest as $result)<div><h3 class="text-sm font-semibold">{{ ['openai' => 'OpenAI', 'gemini' => 'Gemini', 'perplexity' => 'Perplexity'][$result->provider] }}</h3><p class="mt-1 text-sm text-slate-600">{{ $result->status !== 'completed' ? ucfirst($result->status) : ($result->brand_mentioned ? 'Brand mentioned' : 'Brand not mentioned') }}@if ($result->status === 'completed') · {{ $result->website_cited ? 'Domain cited' : 'Domain not cited' }}@endif</p><p class="mt-1 text-xs text-slate-500">{{ $result->checked_at?->format('j M Y, H:i') ?? 'No completed result' }}{{ $result->prompt_fingerprint !== $prompt->fingerprint ? ' · Previous prompt wording' : '' }}</p></div>@empty<p class="text-sm text-slate-500">No checks yet.</p>@endforelse</div></section>
    @if ($trend)<x-progress-chart title="Prompt visibility history" description="Completed checks on each observed date, using OpenAI. Old prompt wording remains in history; see each response below." :points="$trend" value-key="score" format="percentage" />@endif
    <section><h2 class="text-lg font-semibold text-slate-950">Check history and evidence</h2><div class="mt-4 space-y-4">@forelse ($results as $result)<article id="result-{{ $result->id }}" class="rounded-xl border border-slate-200 bg-white p-6">
        <div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold text-slate-950">{{ ['openai' => 'OpenAI', 'gemini' => 'Gemini', 'perplexity' => 'Perplexity'][$result->provider] }} · {{ ucfirst($result->status) }}</h3><p class="text-xs text-slate-500">{{ ($result->checked_at ?? $result->created_at)->format('j M Y, H:i') }} · {{ $result->model }}</p></div>
        <p class="mt-3 text-sm text-slate-600">Asked: {{ $result->prompt_snapshot }}</p>
        @if ($result->status === 'completed')
            <dl class="mt-4 flex flex-wrap gap-x-8 gap-y-3 text-sm"><div><dt class="text-slate-500">Brand</dt><dd class="font-medium">{{ $result->brand_mentioned ? 'Mentioned' : 'Not mentioned' }}</dd></div><div><dt class="text-slate-500">Website</dt><dd class="font-medium">{{ $result->website_mentioned ? 'Mentioned' : 'Not mentioned' }}</dd></div><div><dt class="text-slate-500">Citation</dt><dd class="font-medium">{{ $result->website_cited ? 'Domain cited' : 'Domain not cited' }}</dd></div><div><dt class="text-slate-500">List position</dt><dd class="font-medium">{{ $result->brand_position ?? 'Not measurable' }}</dd></div></dl>
            <div class="mt-5 grid gap-5 md:grid-cols-2"><div><h4 class="text-sm font-semibold text-slate-950">Sources supplied by provider</h4><ul class="mt-2 space-y-2 text-sm">@forelse ($result->citations ?? [] as $citation)<li><a href="{{ $citation['url'] }}" target="_blank" rel="noopener noreferrer" class="break-all text-teal-700 hover:underline">{{ $citation['title'] ?: $citation['domain'] }}</a><span class="block text-xs text-slate-500">{{ $citation['domain'] }}</span></li>@empty<li class="text-slate-500">No citation URLs supplied.</li>@endforelse</ul></div><div><h4 class="text-sm font-semibold text-slate-950">Competitors detected</h4><ul class="mt-2 space-y-1 text-sm text-slate-600">@forelse ($result->competitors ?? [] as $competitor)<li>{{ $competitor['position'] ? '#'.$competitor['position'].' · ' : '' }}{{ $competitor['name'] }}</li>@empty<li>No businesses identified in explicit recommendation lists.</li>@endforelse</ul></div></div>
            <details class="mt-5 rounded-lg bg-slate-50 p-4"><summary class="cursor-pointer text-sm font-semibold text-slate-700">Read response and matching evidence</summary><pre class="mt-4 whitespace-pre-wrap break-words font-sans text-sm leading-6 text-slate-700">{{ $result->response_text }}</pre><p class="mt-4 border-t border-slate-200 pt-3 text-xs text-slate-500">Matched names: {{ implode(', ', $result->identity_snapshot['names'] ?? []) }}. Domains: {{ implode(', ', $result->identity_snapshot['domains'] ?? []) }}. Analysis version {{ data_get($result->analysis, 'version', 1) }}. Only explicit ordered lists produce positions; competitor detection is conservative.</p></details>
        @else<p class="mt-3 text-sm text-slate-600">{{ $result->error ?: 'This check has not completed. It does not count toward visibility metrics.' }}</p>@endif
    </article>@empty<p class="rounded-xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">Enable tracking and queue this prompt to collect its first response.</p>@endforelse</div><div class="mt-4">{{ $results->links() }}</div></section>
    @if ($canManage && ! $prompt->trashed())
        <details class="rounded-xl border border-slate-200 bg-white p-6"><summary class="cursor-pointer text-lg font-semibold text-slate-950">Edit prompt</summary><form method="POST" action="{{ route('admin.ai-visibility.update', [$website, $prompt]) }}" class="mt-4 max-w-3xl space-y-4">@csrf @method('PUT') @include('admin.ai-visibility.prompt-fields', ['values' => $prompt])<button class="rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white">Save prompt</button></form></details>
        <div class="flex flex-wrap gap-4"><form method="POST" action="{{ route('admin.ai-visibility.prompt-check', [$website, $prompt]) }}">@csrf<button class="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Check if due</button></form><details><summary class="cursor-pointer px-4 py-2 text-sm text-red-700">Delete prompt</summary><form method="POST" action="{{ route('admin.ai-visibility.destroy', [$website, $prompt]) }}" class="mt-3 rounded-lg border border-red-200 bg-white p-4">@csrf @method('DELETE')<p class="mb-3 text-sm text-slate-600">Stop tracking and remove this prompt from the list. Historical evidence is retained.</p><button class="rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white">Confirm deletion</button></form></details></div>
    @endif
</div>
@endsection
