<section id="join-beta" class="scroll-mt-8 border-t border-ink/10 py-16 sm:py-20">
    <div class="mx-auto grid max-w-7xl items-start gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:px-10">
        <div>
            <p class="font-mono text-base uppercase tracking-wide text-garden sm:text-sm">Join the agency beta</p>
            <h2 class="mt-4 max-w-[24ch] text-balance font-display text-4xl font-semibold tracking-tight sm:text-5xl">Let’s build a service your clients will value.</h2>
            <p class="mt-6 max-w-[48ch] text-pretty text-lg/8 text-ink/70">Tell us about your agency, the websites you look after and what you would like Sitewell to handle. We’ll discuss a suitable pilot and the work involved.</p>
            <p class="mt-5 max-w-[56ch] text-pretty text-base/7 text-ink/60">This is an expression of interest, not an instant account or a commitment to buy. Beta scope, pricing and availability will be discussed with you.</p>
            <a href="tel:+441302248374" class="mt-8 inline-block text-lg font-medium underline decoration-ink/25 underline-offset-4 hover:text-garden">Or call us on 01302 248 374</a>
        </div>
        <div class="min-w-0 rounded-xl bg-white p-6 ring-1 ring-ink/10 sm:p-8">
            @if (session('agency_status'))<p role="status" class="mb-6 rounded-md bg-lichen p-4 text-base/7 text-moss">{{ session('agency_status') }}</p>@endif
            @if ($errors->any())<div role="alert" class="mb-6 rounded-md bg-red-50 p-4 text-base text-red-800"><p class="font-medium">Please check the details below.</p><ul role="list" class="mt-3 grid gap-2">@foreach ($errors->messages() as $field => $messages)<li><a href="#beta-{{ $field }}" class="underline underline-offset-4">{{ $messages[0] }}</a></li>@endforeach</ul></div>@endif
            <form method="POST" action="{{ route('marketing.agencies.store') }}" class="grid gap-6">
                @csrf
                @foreach ([['name', 'Your name', 'text', 'name'], ['agency', 'Agency name', 'text', 'organization'], ['email', 'Work email', 'email', 'email'], ['website', 'Agency website', 'url', 'url'], ['client_websites', 'Approximate number of client websites', 'number', 'off']] as [$field, $label, $type, $autocomplete])
                    <div><label for="beta-{{ $field }}" class="text-base font-medium">{{ $label }}</label><input id="beta-{{ $field }}" name="{{ $field }}" type="{{ $type }}" autocomplete="{{ $autocomplete }}" value="{{ old($field) }}" required @if($type === 'number') min="0" max="100000" step="1" @endif @if($type === 'url') placeholder="https://your-agency.co.uk" @endif aria-invalid="{{ $errors->has($field) ? 'true' : 'false' }}" @error($field) aria-describedby="beta-{{ $field }}-error" @enderror class="mt-2 w-full rounded-md bg-white px-3.5 py-3 text-base ring-1 ring-ink/20 focus:outline-2 focus:-outline-offset-1 focus:outline-garden">@error($field)<p id="beta-{{ $field }}-error" class="mt-2 text-base text-red-700">{{ $message }}</p>@enderror</div>
                @endforeach
                <div><label for="beta-offers_seo" class="text-base font-medium">Do you currently offer SEO?</label><span class="mt-2 grid grid-cols-[1fr_--spacing(8)]"><select id="beta-offers_seo" name="offers_seo" required aria-invalid="{{ $errors->has('offers_seo') ? 'true' : 'false' }}" @error('offers_seo') aria-describedby="beta-offers_seo-error" @enderror class="col-span-full row-start-1 w-full appearance-none rounded-md bg-white px-3.5 py-3 pr-10 text-base ring-1 ring-ink/20 focus:outline-2 focus:-outline-offset-1 focus:outline-garden"><option value="">Please select</option><option value="yes" @selected(old('offers_seo') === 'yes')>Yes</option><option value="no" @selected(old('offers_seo') === 'no')>No</option></select><span aria-hidden="true" class="pointer-events-none col-start-2 row-start-1 place-self-center">⌄</span></span>@error('offers_seo')<p id="beta-offers_seo-error" class="mt-2 text-base text-red-700">{{ $message }}</p>@enderror</div>
                <div><label for="beta-goals" class="text-base font-medium">Anything you’d like Sitewell to handle? <span class="font-normal text-ink/60">(optional)</span></label><textarea id="beta-goals" name="goals" rows="4" maxlength="3000" aria-invalid="{{ $errors->has('goals') ? 'true' : 'false' }}" @error('goals') aria-describedby="beta-goals-error" @enderror class="mt-2 w-full resize-y rounded-md bg-white px-3.5 py-3 text-base ring-1 ring-ink/20 focus:outline-2 focus:-outline-offset-1 focus:outline-garden">{{ old('goals') }}</textarea>@error('goals')<p id="beta-goals-error" class="mt-2 text-base text-red-700">{{ $message }}</p>@enderror</div>
                <div class="absolute -left-9999" aria-hidden="true"><label for="beta-_sitewell_check">Leave this blank</label><input id="beta-_sitewell_check" name="_sitewell_check" tabindex="-1" autocomplete="off"></div>
                <p class="text-pretty text-base/7 text-ink/60">We’ll use these details to respond to your beta enquiry. Read our <a href="{{ route('marketing.privacy') }}" class="underline underline-offset-4 hover:text-garden">privacy policy</a>.</p>
                <button type="submit" class="justify-self-start rounded-md bg-garden px-5 py-3 text-base font-medium text-white hover:bg-moss focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-garden">Join the agency beta <span aria-hidden="true">↗</span></button>
            </form>
        </div>
    </div>
</section>
