@php
    $canManage = $website->isManageableBy(Auth::user());
    $generation = $seoImpact->generation;
    $baseline = data_get($seoImpact->baseline, 'target.totals', []);
    $current = data_get($seoImpact->observations, 'target.totals', []);
@endphp
<div class="space-y-6">
    <header><a class="text-sm font-medium text-teal-700 underline" href="{{ route('admin.websites.section', [$website, 'seo', 'seo_section' => 'impact']) }}">All SEO impact</a><h1 class="mt-3">{{ $seoImpact->title }}</h1><p class="mt-2 text-base text-slate-600 sm:text-sm">Sitewell records the objective, starts tracking at merge, checks the live pages, and prepares the results automatically.</p></header>
    @if ($errors->any())<div role="alert" class="ui-well p-4 text-rose-700"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <section class="ui-panel ui-section" aria-labelledby="automatic-impact-status"><h2 id="automatic-impact-status" class="text-xl font-semibold">{{ $seoImpact->live_at ? 'Tracking this change' : 'Ready to track automatically' }}</h2><p class="mt-3 text-base text-slate-600 sm:text-sm">{{ $seoImpact->automatic_summary ?: 'No manual change log is needed. When the pull request merges, Sitewell uses its merge date as the live date and carries the original brief into the review.' }}</p>
        <dl class="mt-5 grid gap-4 sm:grid-cols-3"><div><dt class="font-medium">Live date</dt><dd class="mt-1 text-base text-slate-600 sm:text-sm">{{ $seoImpact->live_at?->copy()->setTimezone('America/Los_Angeles')->format('j M Y') ?: 'Awaiting merge or Pixel publication' }}</dd></div><div><dt class="font-medium">Page checks</dt><dd class="mt-1 text-base text-slate-600 sm:text-sm">{{ str($seoImpact->verification_status ?: 'Not started')->replace('_', ' ')->ucfirst() }}</dd></div><div><dt class="font-medium">Next search review</dt><dd class="mt-1 text-base text-slate-600 sm:text-sm">{{ $seoImpact->status === 'completed' ? 'Scheduled reviews complete' : ($seoImpact->live_at ? $seoImpact->live_at->copy()->addDays($seoImpact->review_after_days + 3)->format('j M Y').' · week '.intdiv($seoImpact->review_after_days, 7) : 'Four weeks after the change goes live') }}</dd></div></dl>
        @if ($seoImpact->review_available_at && ! $seoImpact->acknowledged_at && $canManage)<div class="mt-5 flex flex-wrap gap-2"><form method="POST" action="{{ route('admin.seo-impacts.acknowledge', [$website, $seoImpact]) }}">@csrf<button type="submit" class="ui-button ui-button-primary">Mark as read</button></form>@if ($seoImpact->suggested_decision !== 'keep' || $seoImpact->verification_status === 'attention')<form method="POST" action="{{ route('admin.seo-impacts.followup', [$website, $seoImpact]) }}">@csrf<button type="submit" class="ui-button ui-button-secondary">Queue a follow-up with this evidence</button></form>@endif</div>@endif
    </section>
    @if ($seoImpact->measurement_error)<p role="status" class="rounded-lg bg-amber-50 p-4 text-base text-amber-900 sm:text-sm">{{ $seoImpact->measurement_error }}</p>@endif
    <section class="ui-panel ui-section"><h2 class="font-semibold">Why this work was chosen</h2><p class="mt-3 whitespace-pre-line text-base text-slate-600 sm:text-sm">{{ $seoImpact->hypothesis }}</p><ul role="list" class="mt-4 space-y-2">@foreach ($seoImpact->target_urls as $url)<li class="break-all text-base sm:text-sm"><a class="text-teal-700 underline" href="{{ route('admin.websites.section', [$website, 'seo', 'seo_section' => 'pages', 'page_url' => $url]) }}">{{ $url }}</a></li>@endforeach</ul>@if ($seoImpact->target_queries)<p class="mt-3 text-base text-slate-500 sm:text-sm">Search terms: {{ implode(', ', $seoImpact->target_queries) }}</p>@endif
        @if ($generation && $canManage && $generation->pull_request_url)<p class="mt-3 text-sm"><a class="font-medium text-teal-700 underline" href="{{ $generation->pull_request_url }}" target="_blank" rel="noopener">Open pull request #{{ $generation->pull_request_number }}</a></p>@endif
        @if ($seoImpact->contentRequest?->optimisations->isNotEmpty())
            <p class="mt-3 text-base text-slate-600 sm:text-sm">Linked Pixel changes:</p><ul class="mt-2 space-y-1 text-sm text-slate-600">@foreach ($seoImpact->contentRequest->optimisations as $optimisation)<li>{{ $optimisation->url }} · {{ $optimisation->status->value }}</li>@endforeach</ul>
        @endif
        @if ($seoImpact->actual_changes)<details class="mt-4"><summary class="cursor-pointer text-sm font-medium">Recorded change details</summary><p class="mt-3 whitespace-pre-line text-base text-slate-600 sm:text-sm">{{ $seoImpact->actual_changes }}</p><p class="mt-2 text-base text-slate-500 sm:text-sm">{{ $seoImpact->deployment_evidence }}</p></details>@endif
    </section>
    <section class="ui-panel ui-section"><h2 class="font-semibold">Live page verification</h2><p class="mt-2 text-base text-slate-600 sm:text-sm">Checks start shortly after merge and retry when a page needs attention. Original audit checks are repeated where available. A passing technical check does not prove a ranking improvement.</p>
        @forelse (data_get($seoImpact->verification, 'pages', []) as $page)<article class="ui-well mt-4 p-4"><h3 class="break-all font-medium">{{ $page['url'] }}</h3><p class="mt-2 text-base text-slate-600 sm:text-sm">{{ ucfirst($page['status']) }} · {{ $page['note'] }}</p>@if (! empty($page['unresolved']))<p class="mt-2 text-base text-amber-800 sm:text-sm">Still unverified: {{ implode(', ', $page['unresolved']) }}</p>@endif</article>@empty<p class="mt-4 text-base text-slate-500 sm:text-sm">{{ $seoImpact->live_at ? 'Waiting for the automatic live page check.' : 'These checks start when the work is published.' }}</p>@endforelse
    </section>
    @include('admin.websites.partials.seo-impact-results')
    @if ($canManage && ($seoImpact->status === 'planned' || $seoImpact->verification_status === 'scope_missing'))<details class="ui-well p-4" @if ($errors->any() || $seoImpact->verification_status === 'scope_missing') open @endif><summary class="cursor-pointer text-sm font-medium">Advanced: adjust tracking scope</summary><div class="mt-4">@include('admin.websites.partials.seo-impact-brief')</div></details>@endif
</div>
