<?php

return [
    'pages' => [
        'white-label-seo' => [
            'label' => 'White-label SEO', 'group' => 'The agency offering', 'kind' => 'service',
            'theme' => 'White label SEO services UK',
            'title' => 'White-label SEO for agencies: your clients, your service | Sitewell',
            'description' => 'Build an ongoing SEO service under your agency relationship. Explore the Sitewell agency beta, delivery responsibilities and our white-label direction.',
            'heading' => 'Your client relationship. An SEO service behind it.',
            'intro' => 'Keep the client relationship while adding SEO. The Sitewell agency beta explores monitoring, reporting and reviewed improvements delivered behind your service.',
            'sections' => [
                ['heading' => 'Decide who owns each part of the service', 'body' => 'A useful white-label arrangement starts with responsibilities. Your agency should own the commercial relationship, the client brief and the conversation about priorities. The delivery process needs a named owner for reviewing findings, approving changes and explaining results. Agree these before selling a monthly package.', 'points' => ['You set the scope and communicate with your client.', 'Agree who authorises access and approves website changes.', 'Make reporting, turnaround and exclusions explicit.']],
                ['heading' => 'Put ongoing work behind the report', 'body' => 'A PDF with a different logo does not maintain a website. Sitewell already brings together scheduled audits, search performance, keyword monitoring and improvement workflows. Those capabilities give your agency evidence to discuss and work to prioritise, rather than another set of charts to interpret.', 'link' => ['white-label-seo-software', 'Explore the software behind the service']],
                ['heading' => 'Be clear about white-label availability', 'body' => 'We are inviting agencies to help shape this offering. Sitewell currently has its own branding. Agency-branded reports, branded client dashboards and custom domains are planned possibilities, not features you can switch on today. The beta conversation is where we agree what can be delivered for your clients now.'],
            ],
            'example' => ['title' => 'Agree the client hand-off before the first audit', 'body' => 'For a fictional design studio taking on a local retailer, the studio could remain the day-to-day contact, collect access and approve the monthly priorities. The first beta discussion would confirm which Sitewell workflows fit the website and who carries out each change.'],
            'faqs' => [['Can I put my logo on Sitewell today?', 'Agency branding is part of the proposed offering, not a current self-service feature. Tell us which client-facing touchpoints matter when you apply.'], ['Will Sitewell take over my client relationship?', 'The agency proposition is designed around you retaining that relationship. Client contact, access and delivery responsibilities will be agreed during beta onboarding.']],
            'related' => ['seo-reseller', 'white-label-seo-software', 'seo-reporting'],
        ],
        'seo-reseller' => [
            'label' => 'Reselling an SEO service', 'group' => 'The agency offering', 'kind' => 'service',
            'theme' => 'SEO reseller UK and reseller SEO services',
            'title' => 'SEO reseller platform for web agencies | Sitewell agency beta',
            'description' => 'Explore how to package and resell ongoing SEO with Sitewell behind your agency. Define deliverables, review time and a sustainable service before you sell.',
            'heading' => 'Build an SEO package you can actually deliver.',
            'intro' => 'Define what clients receive, who does the work and how much review time your agency needs before selling ongoing SEO.',
            'sections' => [
                ['heading' => 'Sell a defined service, not an open-ended promise', 'body' => 'Start with monitoring, a review of the most useful findings and an agreed allowance for improvements. Explain which websites and integrations you can support. Treat migrations, large rewrites and specialist work as separate conversations rather than quietly absorbing them into a retainer.', 'points' => ['State the review and reporting cadence.', 'Set the amount of implementation and revision time.', 'Keep rankings and lead volumes out of contractual promises.']],
                ['heading' => 'Price the whole delivery process', 'body' => 'Your costs include the platform, onboarding, client meetings, editorial review and technical work. An attractive reseller price means little if every account needs unplanned hours. Measure a small pilot before you roll a package out across your client base.', 'link' => ['add-recurring-revenue', 'Work through the recurring revenue model']],
                ['heading' => 'Use the beta to test your offer', 'body' => 'Sitewell already supports the monitoring and improvement workflows that underpin an ongoing service. The agency beta is an opportunity to agree a workable delivery model around them. Agency pricing, reseller terms and service levels are not published packages yet.', 'link' => ['white-label-seo', 'Understand how the white-label relationship works']],
            ],
            'example' => ['title' => 'A practical first package', 'body' => 'An illustrative offer could include regular website checks, tracking agreed keywords, a monthly priorities review and a defined amount of approved improvement work. Specify separately whether new copy, publishing and Google Business Profile work are included.'],
            'faqs' => [['Is there a fixed reseller discount?', 'Agency commercial terms are being explored during the beta. We have not published a reseller margin or minimum-volume commitment.'], ['Can I promise a first-page ranking?', 'No. Sell a clear process and useful work. Search results depend on competition, the website, demand and decisions outside either agency’s control.']],
            'related' => ['white-label-seo', 'add-recurring-revenue', 'seo-for-existing-clients'],
        ],
        'white-label-seo-software' => [
            'label' => 'The platform', 'group' => 'The agency offering', 'kind' => 'service', 'visual' => 'portfolio',
            'theme' => 'White label SEO software and SEO platform for agencies',
            'title' => 'SEO software for agencies, beyond reporting | Sitewell',
            'description' => 'See how Sitewell connects website audits, rankings, search insights and reviewed improvements. Explore the platform and what agency branding still needs to deliver.',
            'heading' => 'From a website problem to the next useful action.',
            'intro' => 'Review client website health, search performance and the work that needs attention in Sitewell.',
            'sections' => [
                ['heading' => 'Bring the evidence into one website workspace', 'body' => 'Sitewell has website health reports, target keyword tracking, Search Console insights and connected Google Business Profile information. You can give people access to specific websites and switch between the sites they can access. Features depend on the plan and the connections configured for that website.'],
                ['heading' => 'Move beyond finding the issue', 'body' => 'Improvement workflows support reviewed page optimisations and content work. The delivery route depends on how a website is connected: supported Pixel changes and repository-based work have different limits. We assess compatibility before promising that a task can be carried out.', 'link' => ['automate-seo', 'See where automation helps and where review stays']],
                ['heading' => 'Help shape the agency layer', 'body' => 'The underlying website tools exist. A dedicated agency portfolio experience, agency-branded client dashboards, branded reports and custom domains remain proposed additions. The preview below shows a direction for that experience, not a screen available in your account today.'],
            ],
            'example' => ['title' => 'One issue, a traceable workflow', 'body' => 'An audit might flag an unclear page title. The agency checks the page’s purpose and search data, reviews an appropriate change, then follows its delivery status. A proposed change should remain distinguishable from a published improvement.'],
            'faqs' => [['Is this a reporting-only tool?', 'No. Reporting sits alongside auditing, monitoring, opportunity discovery and supported improvement workflows. Human review and website compatibility still matter.'], ['Can every website receive automatic code changes?', 'No. The available delivery options depend on the website setup and permissions. Customer-owned repository execution is still being developed and is not part of this launch.']],
            'related' => ['manage-multiple-websites', 'seo-audits', 'automate-seo'],
        ],
        'seo-reporting' => [
            'label' => 'Client SEO reporting', 'group' => 'Monitoring and delivery', 'kind' => 'service', 'visual' => 'report',
            'theme' => 'White label SEO reports and automated client reporting',
            'title' => 'SEO reporting for agencies: explain the work and results | Sitewell',
            'description' => 'Turn rankings, search data, website issues and completed improvements into a useful client update. Explore Sitewell summaries and our agency-branded report direction.',
            'heading' => 'Give clients an update they can understand.',
            'intro' => 'Show clients what changed, what you did and what comes next. Use the numbers to explain the progress.',
            'sections' => [
                ['heading' => 'Answer the questions clients actually ask', 'body' => 'Is the website being found? Are important pages improving? What work happened this week? Sitewell’s weekly summaries bring together available search performance, tracked keyword movements, website health, opportunities and recorded completed work. Missing connections should be explained, not dressed up as zero performance.', 'points' => ['Separate observations from work completed.', 'Explain the comparison period and any missing data.', 'End with a small number of practical next steps.']],
                ['heading' => 'Keep activity and results separate', 'body' => 'Publishing a page is an activity. A rise in relevant search clicks is an outcome. Neither proves the other caused it. Use a report to show both, give changes time to settle and ask the client about enquiry quality. Avoid claiming a proposed or pending change is already live.', 'link' => ['seo-audits', 'Connect the report to ongoing website checks']],
                ['heading' => 'Agency branding is the next layer', 'body' => 'Sitewell’s current reporting exists under the Sitewell brand. Agency logos, branded report delivery and a branded client portal are not current options. The preview illustrates the kind of concise update we want agencies to help shape in the beta.'],
            ],
            'example' => ['title' => 'A useful sentence beats a page of unexplained charts', 'body' => 'Illustrative wording: “More people saw your kitchen fitting page this week, but clicks were steady. We reviewed its search appearance. Next we need your approval for the revised description.” That distinguishes the observation, the work and the decision.'],
            'faqs' => [['Are weekly summaries available now?', 'Yes, Sitewell has weekly summary reporting using the data available for each connected website. The agency-branded version is still a proposed addition.'], ['Can reports show revenue attributed to SEO?', 'Do not assume that. Search visibility and website activity do not by themselves prove revenue. Add the client’s own enquiry and sales evidence when discussing business results.']],
            'related' => ['seo-audits', 'rank-tracking', 'seo-client-retention'],
        ],
        'seo-audits' => [
            'label' => 'Ongoing website audits', 'group' => 'Monitoring and delivery', 'kind' => 'service',
            'theme' => 'White label SEO audit and website audit tool for agencies',
            'title' => 'SEO audits for agencies: keep checking after launch | Sitewell',
            'description' => 'Make website auditing part of an ongoing client service. Find issues, prioritise meaningful fixes and review changes with Sitewell’s scheduled website checks.',
            'heading' => 'The launch audit is only the starting point.',
            'intro' => 'Regular audits flag broken links, missing information and technical issues across client websites.',
            'sections' => [
                ['heading' => 'Create a baseline you can revisit', 'body' => 'Use the first report to understand the pages checked and the issues found. Agree which parts of the site matter commercially. Future checks are more useful when you can distinguish a new issue from an accepted limitation or a task already waiting for approval.'],
                ['heading' => 'Prioritise the business page, not just the score', 'body' => 'A broken service-page journey can matter more than a collection of minor warnings. Sitewell’s website health reports surface issues and opportunities, but the agency still supplies context: which services matter, what changed recently and what the client can realistically approve.', 'points' => ['Review crawl coverage before calling an audit complete.', 'Group repeated issues by their likely underlying cause.', 'Confirm a fix with a fresh check after delivery.']],
                ['heading' => 'Turn findings into a repeatable work queue', 'body' => 'Scheduled checks reduce the work of rediscovering problems. Reviewed improvements can then use the delivery options available for the site. An audit is evidence for a decision, not permission to change everything automatically.', 'link' => ['automate-seo', 'Build a sensible automation workflow']],
            ],
            'example' => ['title' => 'Catch a regression after a content update', 'body' => 'A fictional trades website adds several service pages. The next check flags a broken internal link. The agency confirms the destination, arranges the fix and rechecks it, giving the client a concrete account of the ongoing care.'],
            'faqs' => [['Does an audit cover every page of any size website?', 'Coverage depends on crawl settings, access and the site itself. Check the pages included before making a whole-site claim, especially for large or restricted websites.'], ['Are audits already white-labelled?', 'Website audits are available in Sitewell. Agency-branded audit presentation is part of the proposed agency offering.']],
            'related' => ['automate-seo', 'seo-reporting', 'manage-multiple-websites'],
        ],
        'rank-tracking' => [
            'label' => 'Keyword monitoring', 'group' => 'Monitoring and delivery', 'kind' => 'service',
            'theme' => 'Agency rank tracking and client keyword tracking',
            'title' => 'Rank tracking for agencies and client websites | Sitewell',
            'description' => 'Monitor agreed client keywords, spot meaningful movement and turn ranking checks into useful conversations. Keep location, timing and search context clear.',
            'heading' => 'Track the searches that matter to each client.',
            'intro' => 'Track agreed keywords for each client’s services and locations, then use the results to plan page improvements.',
            'sections' => [
                ['heading' => 'Agree the target before measuring movement', 'body' => 'Choose specific terms with the client and match them to relevant pages. Keep the location and check settings consistent so a comparison has meaning. Sitewell supports target keywords and ranking history for individual websites; paid data checks require configuration and the appropriate access.'],
                ['heading' => 'Read movement in context', 'body' => 'One changed position is a signal to investigate, not a result to celebrate in isolation. Look for repeated movement across relevant terms and consider whether the right page is appearing. A term outside the checked results should not be presented as a precise position.', 'points' => ['Prioritise relevant terms close to stronger visibility.', 'Investigate sustained drops alongside website changes.', 'Keep desktop organic checks distinct from Maps rankings.']],
                ['heading' => 'Use rankings to improve the client conversation', 'body' => 'Combine position changes with Search Console clicks and the work completed. Explain the date of the observation and why the term matters. The report should help the client make a decision rather than encourage them to watch a ranking every hour.', 'link' => ['seo-reporting', 'Turn keyword movement into a clear client update']],
            ],
            'example' => ['title' => 'A position change is the start of a question', 'body' => 'If an illustrative “boiler repair Doncaster” check moves from 14 to 7, ask whether the service page also receives more relevant clicks. Keep that example separate from promises: it is fictional data, not a Sitewell customer result.'],
            'faqs' => [['Is this Google Maps grid tracking?', 'No. Sitewell’s target-keyword checks monitor desktop organic search results. They should not be sold as a local Maps grid product.'], ['Can a ranking guarantee more enquiries?', 'No. Position, search demand, the search result and the landing page all affect what happens next. Discuss enquiries separately with the client.']],
            'related' => ['seo-reporting', 'google-search-console', 'seo-for-existing-clients'],
        ],
        'google-search-console' => [
            'label' => 'Search Console insights', 'group' => 'Monitoring and delivery', 'kind' => 'service',
            'theme' => 'Google Search Console reporting for agencies',
            'title' => 'Google Search Console insights for agencies | Sitewell',
            'description' => 'Use client Search Console data to understand visibility, clicks and page opportunities. Sitewell helps agencies turn search data into a practical next step.',
            'heading' => 'Turn Search Console data into a useful next step.',
            'intro' => 'Use Search Console to see which pages appear in search, which earn clicks and where to improve.',
            'sections' => [
                ['heading' => 'Connect the right property with permission', 'body' => 'Sitewell connects to Google Search Console so authorised users can review website search performance. Confirm that the selected property covers the client’s actual website. Missing access or incomplete history should be resolved before you build a narrative around the numbers.'],
                ['heading' => 'Separate visibility from visits', 'body' => 'Impressions show appearances in search results; clicks show visits from those results. Average position is an aggregate, not a fixed rank for every searcher. Compare meaningful periods and account for seasonality, changed pages and the mix of queries.', 'points' => ['Look for relevant pages with impressions but few clicks.', 'Separate branded demand from discovery searches.', 'Check whether a fall affects the whole site or a few pages.']],
                ['heading' => 'Turn an opportunity into a reviewed change', 'body' => 'A relevant page with weak click-through may deserve a clearer title or description. A recurring query may reveal a missing explanation. Sitewell helps surface opportunities; your agency verifies intent, agrees the work and reviews delivery rather than treating every suggestion as an instruction.', 'link' => ['seo-reporting', 'Explain the evidence in your client report']],
            ],
            'example' => ['title' => 'Do not mistake changing demand for a broken website', 'body' => 'For a fictional holiday business, fewer autumn clicks may reflect seasonal demand. Compare the relevant pages and periods before recommending a rewrite. Search data becomes useful when it is read alongside what the business actually sells.'],
            'faqs' => [['Does the client need to grant Google access?', 'Yes. The relevant Search Console property must be connected through an account with permission to access it.'], ['Is Search Console average position the same as rank tracking?', 'No. Search Console aggregates impressions across searches. A configured rank check observes a particular query and context. They answer different questions.']],
            'related' => ['rank-tracking', 'seo-reporting', 'automate-seo'],
        ],
        'google-business-profile' => [
            'label' => 'Google Business Profile', 'group' => 'Monitoring and delivery', 'kind' => 'service',
            'theme' => 'Google Business Profile reporting for agencies and local SEO',
            'title' => 'Google Business Profile reporting for agencies | Sitewell',
            'description' => 'Bring connected Google Business Profile performance, reviews and updates into your local client service. Keep profile activity and website performance in context.',
            'heading' => 'Keep the local business in the picture.',
            'intro' => 'Review a local client’s website and Google Business Profile together, while keeping their different metrics clear.',
            'sections' => [
                ['heading' => 'Start with the correct location', 'body' => 'Connect an authorised Google account and select the relevant business location. Sitewell can use available profile performance in the website’s reporting. Confirm access and location selection first; a missing connection is not evidence that the business has no visibility.'],
                ['heading' => 'Make local visibility part of routine care', 'body' => 'The existing profile tools include performance information, reviews, posts and recommendations. Your agency can use these to keep local information and communication under review. Agree who confirms facts such as opening hours and who approves public-facing wording.', 'points' => ['Review information when the business changes.', 'Keep review replies specific and appropriate.', 'Check the status of a proposed update before reporting it as published.']],
                ['heading' => 'Explain the limits of local reporting', 'body' => 'Profile interactions, website search clicks and enquiries describe different parts of the customer journey. Do not add them together as unique customers. These features are not a Maps grid ranking product, and access to individual metrics depends on the connected profile.', 'link' => ['seo-reporting', 'Bring local performance into a clear weekly summary']],
            ],
            'example' => ['title' => 'Give seasonal changes an owner', 'body' => 'A fictional garden centre changes its opening hours for winter. The agency checks the website and profile information, agrees the wording with the client and follows the update through. That is useful local care even when a ranking chart barely changes.'],
            'faqs' => [['Can I manage profiles without client permission?', 'No. You need an authorised connection to the relevant business location. Confirm permissions as part of onboarding.'], ['Does Sitewell guarantee a Maps position?', 'No. Profile care and reporting do not guarantee a search placement. Maps grid tracking is not included in the capabilities described here.']],
            'related' => ['seo-reporting', 'seo-for-existing-clients', 'rank-tracking'],
        ],
        'offer-seo-without-hiring' => [
            'label' => 'Offer SEO without hiring', 'group' => 'Build your service', 'kind' => 'article',
            'theme' => 'Offer SEO without hiring an SEO team',
            'title' => 'How to offer SEO without hiring an SEO team | Sitewell',
            'description' => 'A practical route for web agencies adding SEO: start with a narrow service, automate routine monitoring and keep review and specialist decisions clearly owned.',
            'heading' => 'Add SEO before you add a whole new department.',
            'intro' => 'Offer ongoing SEO with specialist support. Agree which work your agency handles and which work you need help delivering.',
            'sections' => [
                ['heading' => 'Begin with work you can explain', 'body' => 'Offer a baseline review, agreed keyword monitoring, regular checks and a prioritised improvement plan. Avoid selling a broad “everything SEO” package before you know how it will be delivered. A narrow, reliable service is easier to price and easier for a client to understand.'],
                ['heading' => 'Separate repetitive work from judgement', 'body' => 'Collecting metrics and repeating website checks are good candidates for automation. Deciding which services to promote, reviewing claims in new copy and approving changes need business context. Name an account owner even when software handles much of the routine work.', 'points' => ['Allocate time to review findings and client questions.', 'Bring in specialists for migrations or unfamiliar technical problems.', 'Agree how issues outside the package will be quoted.']],
                ['heading' => 'Run a small pilot before expanding', 'body' => 'Choose a few clients with clear goals and manageable websites. Record onboarding time, monthly review effort and extra work. Sitewell’s agency beta gives you a way to explore monitoring and delivery workflows while testing whether the service fits your team.', 'link' => ['seo-reseller', 'Define a repeatable SEO package']],
            ],
            'example' => ['title' => 'Start with three existing maintenance clients', 'body' => 'Choose clients you already know, agree one priority for each and run a consistent review cycle. After that cycle, compare the time spent with what you priced. Expand only when the work and responsibilities are repeatable.'],
            'faqs' => [['Does software remove the need for SEO knowledge?', 'No. It reduces repetitive work and brings evidence together. Someone still needs to understand the recommendations, recognise the limits and make appropriate decisions.'], ['When should I use a specialist?', 'When the work exceeds your competence or available time, particularly complex migrations, sensitive content or difficult technical diagnosis. Include that hand-off in the service plan.']],
            'related' => ['automate-seo', 'seo-reseller', 'seo-for-web-designers'],
        ],
        'add-recurring-revenue' => [
            'label' => 'Build recurring revenue', 'group' => 'Build your service', 'kind' => 'article',
            'theme' => 'Recurring SEO revenue for web agencies',
            'title' => 'Turn website clients into recurring SEO revenue | Sitewell',
            'description' => 'Explore an ongoing SEO service for your existing website clients. Model delivery costs, review time and capacity before treating monthly revenue as profit.',
            'heading' => 'Your next service could start with clients you already have.',
            'intro' => 'Add ongoing SEO to your existing client relationships with clear deliverables and a regular review process.',
            'sections' => [
                ['heading' => 'Look for a real ongoing need', 'body' => 'Start with clients whose websites matter to new business and whose teams want to improve them. Some will only need maintenance; others have clear visibility problems or unused content opportunities. Do not assume every maintenance client wants or needs an SEO retainer.'],
                ['heading' => 'Model contribution, not just monthly sales', 'body' => 'Use a simple calculation: client fees minus platform and data costs, delivery time, account management and specialist support. Onboarding takes time too. Keep an allowance for revisions and unexpected issues, and distinguish that contribution from profit after all your agency overheads.', 'points' => ['Estimate take-up rather than assuming every client buys.', 'Measure review and implementation hours during a pilot.', 'Revisit scope when delivery effort exceeds the allowance.']],
                ['heading' => 'Build a service clients can keep choosing', 'body' => 'A retainer lasts when the client understands what is being monitored, what work happened and what is next. Sitewell’s ongoing checks and reporting can support that rhythm. Agency pricing is still being explored, so validate your model against agreed beta terms before quoting a wider rollout.', 'link' => ['seo-for-existing-clients', 'Introduce the service to existing clients']],
            ],
            'example' => ['title' => 'An illustrative planning calculation', 'body' => 'If 5 of 30 clients choose a service at £200 per month, that is £1,000 in monthly revenue before costs. Subtract your agreed platform costs, delivery hours and overheads. These are hypothetical figures, not Sitewell pricing, expected take-up or an earnings forecast.'],
            'faqs' => [['What margin should I expect?', 'There is no reliable universal margin. Your scope, client complexity, time costs and agreed platform terms determine whether the service works commercially.'], ['Should I offer SEO to every client immediately?', 'Identify good-fit clients first. A small pilot reveals delivery costs and client expectations before you commit your wider portfolio.']],
            'related' => ['seo-for-existing-clients', 'seo-reseller', 'seo-client-retention'],
        ],
        'seo-for-existing-clients' => [
            'label' => 'Sell SEO to existing clients', 'group' => 'Build your service', 'kind' => 'article',
            'theme' => 'How to sell SEO to existing web design clients',
            'title' => 'How to introduce SEO to existing website clients | Sitewell',
            'description' => 'Start an SEO conversation with evidence, a useful explanation and a manageable first step. A practical guide for agencies with existing web design clients.',
            'heading' => 'Start with their website. Not a sales pitch.',
            'intro' => 'Start the SEO conversation with a specific website opportunity tied to the client’s business goals.',
            'sections' => [
                ['heading' => 'Choose clients with a reason to act', 'body' => 'Look for a service they want to grow, a recent change in the business or a website that has not been reviewed since launch. Ask about enquiry quality and capacity. More demand is not useful if the client cannot serve it, and a website issue is not always an SEO issue.'],
                ['heading' => 'Show one finding and explain its consequence', 'body' => 'Use an audit or authorised search data to illustrate the problem. Translate it into plain English: an important service is hard to find, a page does not answer a common question, or a useful search result receives few clicks. Avoid overwhelming the client with an export of warnings.', 'points' => ['Explain what you know and what still needs checking.', 'Tie the first recommendation to a relevant service or page.', 'Offer a clear scope, review point and approval process.']],
                ['heading' => 'Make the next step easy to evaluate', 'body' => 'Propose a defined baseline and a short list of priorities. Explain how ongoing reviews will work and what the client needs to supply. Sitewell can support the evidence and monitoring behind this conversation; your relationship and knowledge of the business remain central.', 'link' => ['add-recurring-revenue', 'Plan the delivery economics before quoting']],
            ],
            'example' => ['title' => 'A straightforward opening', 'body' => '“You mentioned wanting more commercial work. Your commercial service page is quite hard to reach from the rest of the site. Would it help if we reviewed that page and the searches bringing people to it, then agreed what to improve?”'],
            'faqs' => [['Should I give away a full strategy?', 'Offer enough evidence to make the problem understandable. Keep detailed research and implementation within a clearly agreed scope rather than promising unlimited unpaid work.'], ['What if the client expects immediate results?', 'Agree realistic review periods and explain what can be delivered now versus what needs time to measure. Do not turn uncertainty into a ranking guarantee.']],
            'related' => ['add-recurring-revenue', 'seo-audits', 'seo-reporting'],
        ],
        'manage-multiple-websites' => [
            'label' => 'Manage a client portfolio', 'group' => 'Build your service', 'kind' => 'service', 'visual' => 'portfolio',
            'theme' => 'Manage multiple client websites and agency website management',
            'title' => 'Managing multiple client websites with Sitewell | Agency beta',
            'description' => 'Create a repeatable review process across client websites. Explore Sitewell website workspaces, permissions and the proposed agency portfolio experience.',
            'heading' => 'Give every client website a place in the process.',
            'intro' => 'Keep track of which client websites need attention, who owns each task and what happens next.',
            'sections' => [
                ['heading' => 'Keep access specific to each website', 'body' => 'Sitewell supports multiple website relationships, a website switcher and manager or viewer access. People should only see the sites they are authorised to access. Agree responsibility for connections, reviews and approvals when a client joins your service.'],
                ['heading' => 'Use the same questions across different sites', 'body' => 'Has a new issue appeared? Have important keywords moved? Is work waiting for approval? Which client needs a conversation? A shared review rhythm reduces missed follow-ups even when the sites use different technology and need different work.', 'points' => ['Confirm monitoring and integrations at onboarding.', 'Review unresolved issues alongside recent work.', 'Keep data gaps visible instead of assuming a site is healthy.']],
                ['heading' => 'The portfolio view is a beta direction', 'body' => 'Today’s customer experience centres on individual website workspaces. A consolidated agency dashboard like the preview is not yet available. We want agency feedback on cross-client priorities, reporting and how teams should share responsibility.', 'link' => ['white-label-seo-software', 'Explore the existing platform and planned agency layer']],
            ],
            'example' => ['title' => 'A Monday review with a purpose', 'body' => 'A fictional agency starts with clients awaiting decisions, then checks new issues and completed work. Healthy sites still receive routine monitoring; they simply do not need the same attention as a failed connection or an unresolved service-page problem.'],
            'faqs' => [['Can customers already use the previewed portfolio dashboard?', 'No. It is an agency beta concept. Existing access uses website-specific workspaces and a switcher, with permissions for each website.'], ['Is Sitewell a hosting control panel?', 'No. Website management here means monitoring, insights and supported improvement workflows. Hosting, backups and arbitrary server administration should be scoped separately.']],
            'related' => ['white-label-seo-software', 'seo-audits', 'seo-for-wordpress-agencies'],
        ],
        'automate-seo' => [
            'label' => 'Automate routine SEO work', 'group' => 'Build your service', 'kind' => 'article',
            'theme' => 'SEO automation for agencies and automated client SEO',
            'title' => 'SEO automation for agencies, with review built in | Sitewell',
            'description' => 'Decide what to automate in client SEO and what needs human judgement. Use Sitewell for repeated checks, monitoring and reviewed improvement workflows.',
            'heading' => 'Automate the repetition. Keep the decisions yours.',
            'intro' => 'Automate repeat checks and reporting. Keep people responsible for priorities, approvals and client advice.',
            'sections' => [
                ['heading' => 'Start with checks and evidence collection', 'body' => 'Scheduled audits, configured keyword observations and search summaries reduce repetitive analysis. They give an agency a consistent starting point for review. Automation still depends on valid connections, configured schedules and data being available.'],
                ['heading' => 'Keep business judgement with a person', 'body' => 'A tool cannot decide which services a client wants to stop selling or verify every claim in a new article. Your team should set priorities, check accuracy and approve work that affects the brand. Sensitive, regulated or commercially important content deserves particular care.', 'points' => ['Review content for accuracy and relevance.', 'Agree implementation permissions and rollback options.', 'Escalate unusual issues rather than repeating a failing workflow.']],
                ['heading' => 'Distinguish a draft from delivery', 'body' => 'Sitewell supports opportunities, content workflows and reviewed improvements through configured delivery routes. A generated draft is not a published article, and an open pull request is not a deployed change. Use the recorded status when reporting progress.', 'link' => ['seo-reporting', 'Show clients what has actually been completed']],
            ],
            'example' => ['title' => 'A workflow worth automating', 'body' => 'Schedule a website check, gather relevant search evidence and prepare a recommendation. Then have the agency review its purpose and wording before using the supported delivery route. Recheck afterwards; automation should shorten the process, not remove accountability.'],
            'faqs' => [['Can I promise fully automated SEO?', 'No. Strategy, client priorities, factual accuracy and approval still need judgement. Describe the specific repeated tasks your service automates.'], ['Will every suggested improvement be published automatically?', 'No. Review, permissions and the website’s supported delivery route determine what happens. Confirm those steps for each client before agreeing a package.']],
            'related' => ['seo-audits', 'offer-seo-without-hiring', 'white-label-seo-software'],
        ],
        'seo-client-retention' => [
            'label' => 'Keep the client conversation going', 'group' => 'Build your service', 'kind' => 'article',
            'theme' => 'SEO client retention and ongoing agency relationships',
            'title' => 'Use ongoing SEO to strengthen client relationships | Sitewell',
            'description' => 'Give clients a useful reason to hear from your agency after launch. Build a consistent review rhythm around website health, opportunities and completed work.',
            'heading' => 'Give clients a reason to talk after launch.',
            'intro' => 'Keep working with clients after launch through regular SEO reviews, content and website improvements.',
            'sections' => [
                ['heading' => 'Replace the annual check-in with useful contact', 'body' => 'A short update on a relevant page, an issue caught or a decision needed is more useful than a generic “just checking in”. Use monitoring to find reasons for a conversation, not excuses to send another automated email.'],
                ['heading' => 'Make quiet months understandable', 'body' => 'Not every month brings a dramatic improvement. Explain what was checked, what stayed stable and why a planned task is waiting. Being clear about uncertainty protects trust better than dressing routine activity up as a breakthrough.', 'points' => ['Show completed work and pending approvals separately.', 'Ask whether business priorities or capacity have changed.', 'Agree the next review and who owes the next action.']],
                ['heading' => 'Earn renewal through a clear service', 'body' => 'Sitewell’s summaries and work records can support your account reviews. Retention still depends on fit, delivery and communication. Do not treat a dashboard login as proof that the client sees value; use their feedback to improve the service.', 'link' => ['seo-reporting', 'Build a client update around useful evidence']],
            ],
            'example' => ['title' => 'A renewal conversation with something to discuss', 'body' => 'Review the client’s original priorities, work delivered, unresolved issues and changes in search visibility. Then ask what the business needs next. That gives both sides a better basis for renewing than a list of software features.'],
            'faqs' => [['Will ongoing SEO guarantee better retention?', 'No. It can support a more useful relationship, but renewal depends on the client’s needs, your delivery and the value they perceive.'], ['How often should I contact clients?', 'Agree a cadence that fits the service and the client. Routine summaries can support it, while significant issues or decisions may need a direct conversation sooner.']],
            'related' => ['seo-reporting', 'add-recurring-revenue', 'seo-for-existing-clients'],
        ],
        'seo-for-web-designers' => [
            'label' => 'For web designers', 'group' => 'For your agency', 'kind' => 'service',
            'theme' => 'SEO for web designers and freelance designers',
            'title' => 'SEO for web designers without building a team | Sitewell',
            'description' => 'Add a manageable ongoing SEO service to your web design work. Explore a focused offer for freelance designers and small studios in the Sitewell agency beta.',
            'heading' => 'Keep looking after the websites you design.',
            'intro' => 'Explore the agency beta for web designers who want to offer ongoing SEO alongside website projects.',
            'sections' => [
                ['heading' => 'Start with the clients you know well', 'body' => 'You already understand their pages, services and brand. Use that context to identify a small number of clients who would benefit from ongoing review. Begin with a service you can explain confidently rather than offering every SEO discipline at once.'],
                ['heading' => 'Protect your design time', 'body' => 'Set a fixed review rhythm and an explicit allowance for improvements. Sitewell’s checks and summaries can reduce preparation, but you still need time for client questions and approval. Keep major redesigns and large content projects outside the monthly allowance.', 'points' => ['Choose a small pilot alongside your project schedule.', 'Batch routine reviews without ignoring urgent issues.', 'Define when specialist support is needed.']],
                ['heading' => 'Build a more balanced business', 'body' => 'Ongoing work can complement project income when delivery is priced realistically. Track the hours spent and review the scope as you learn. The agency beta is a chance to shape a service around a small studio’s capacity.', 'link' => ['add-recurring-revenue', 'Plan recurring revenue around real delivery costs']],
            ],
            'example' => ['title' => 'A handover that opens the next conversation', 'body' => 'At the end of a brochure-site project, explain which pages should attract enquiries and offer to review their performance after launch. A defined follow-up is a natural extension of the design work, without making an unsupported promise about traffic.'],
            'faqs' => [['Do I need a large client portfolio?', 'No fixed portfolio minimum is being advertised for the beta. Tell us how many sites you look after and what a manageable pilot would look like.'], ['Can I keep designing while offering SEO?', 'That depends on scope and capacity. Automation reduces repeated checks, but allow time for review, communication and work that cannot be automated.']],
            'related' => ['add-recurring-revenue', 'offer-seo-without-hiring', 'seo-for-existing-clients'],
        ],
        'seo-for-web-development-agencies' => [
            'label' => 'For development agencies', 'group' => 'For your agency', 'kind' => 'service',
            'theme' => 'SEO for web development agencies and technical teams',
            'title' => 'SEO for web development agencies | Sitewell agency beta',
            'description' => 'Connect client SEO evidence to your development process. Explore audits, search opportunities and reviewed changes without bypassing technical ownership.',
            'heading' => 'Turn search findings into work your team can review.',
            'intro' => 'Give your developers clear SEO priorities, backed by website checks and search data.',
            'sections' => [
                ['heading' => 'Give technical work a business reason', 'body' => 'An audit warning becomes more useful when it is tied to an important page, a search opportunity or a broken journey. Start with the evidence, then define the smallest useful change and how your team will check it. Avoid turning every warning into a development ticket.'],
                ['heading' => 'Keep your review and release process', 'body' => 'Existing repository-based workflows prepare changes for review on supported connections. A pull request still needs the appropriate checks and approval; it is not proof of deployment. Client-owned repository connections and SDK execution are being developed separately and are not being offered as a finished capability here.', 'points' => ['Confirm repository access and delivery compatibility first.', 'Keep tests, staging and release ownership explicit.', 'Record what shipped separately from what was proposed.']],
                ['heading' => 'Scope the site before quoting the service', 'body' => 'Framework, page count, content sources and deployment arrangements all affect effort. Use the agency beta to assess representative sites rather than promising arbitrary changes to any stack. Monitoring may be possible where automated implementation is not.', 'link' => ['automate-seo', 'Set sensible boundaries for automation']],
            ],
            'example' => ['title' => 'A focused fix beats an unbounded rewrite', 'body' => 'For an illustrative service page, agree the title change, the supporting evidence and the validation needed. Review it through the team’s normal process. A migration or application redesign belongs in a separate project scope.'],
            'faqs' => [['Can clients connect any GitHub or Bitbucket repository today?', 'No. Broader customer-owned repository support is in development. Assess the existing supported connection options before including implementation in an agency offer.'], ['Will Sitewell merge and deploy changes for us?', 'Do not assume that. Repository work is review-led, and release responsibilities depend on the configured website workflow. Keep your team’s approvals explicit.']],
            'related' => ['white-label-seo-software', 'automate-seo', 'manage-multiple-websites'],
        ],
        'seo-for-wordpress-agencies' => [
            'label' => 'For WordPress agencies', 'group' => 'For your agency', 'kind' => 'service',
            'theme' => 'SEO tools and white label SEO for WordPress agencies',
            'title' => 'SEO for WordPress agencies and maintenance teams | Sitewell',
            'description' => 'Add search visibility and ongoing website review to your WordPress maintenance service. Explore Sitewell’s agency beta and check compatibility before delivery.',
            'heading' => 'Add search visibility to your WordPress care plans.',
            'intro' => 'Add search reviews and page improvements alongside your existing WordPress maintenance service.',
            'sections' => [
                ['heading' => 'Keep maintenance and SEO responsibilities clear', 'body' => 'Backups, plugin updates and security remain part of your existing maintenance arrangements. Sitewell adds website checks, search insights and supported improvement workflows; it is not a replacement for every WordPress management tool or hosting service.'],
                ['heading' => 'Review pages, not just the plugin checklist', 'body' => 'A well-configured SEO plugin does not guarantee that a service page answers the right questions. Use audits and search evidence to review content, internal links and visibility. Agree priorities with the client before adding more pages or changing important copy.', 'points' => ['Monitor relevant pages after content or theme changes.', 'Connect Search Console with the client’s permission.', 'Keep editorial approval alongside technical checks.']],
                ['heading' => 'Check the delivery route for each installation', 'body' => 'Sitewell has a WordPress integration, but themes, plugins, dynamic journeys and publishing arrangements differ. Confirm compatibility and test the proposed workflow before including implementation in a retainer. Sitewell also supports monitoring beyond WordPress, so mixed portfolios can be assessed in the beta.', 'link' => ['manage-multiple-websites', 'Plan a review process across your client websites']],
            ],
            'example' => ['title' => 'Add value beyond an update receipt', 'body' => 'Alongside a routine care-plan update, discuss a service page that is attracting impressions but few clicks. Review its purpose and search appearance with the client. That gives a business reason for further work instead of simply reporting that plugins are current.'],
            'faqs' => [['Does Sitewell replace WordPress hosting and backups?', 'No. Keep those responsibilities with your agreed hosting and maintenance services. Assess Sitewell for monitoring and supported improvement workflows.'], ['Does every WordPress site support the same changes?', 'No. Compatibility depends on the site and connection. Assess representative sites, especially stores and sites with dynamic features, before promising a delivery workflow.']],
            'related' => ['seo-audits', 'manage-multiple-websites', 'seo-for-existing-clients'],
        ],
    ],
];
