<?php

return [
    'default_recipient' => env('FORMS_DEFAULT_RECIPIENT', 'hello@example.com'),
    'from_address' => env('FORMS_FROM_ADDRESS', 'hello@example.com'),
    'from_name' => env('FORMS_FROM_NAME', 'Central Forms'),
    'auto_register_websites' => filter_var(env('FORMS_AUTO_REGISTER_WEBSITES', true), FILTER_VALIDATE_BOOL),
    'auto_register_forms' => filter_var(env('FORMS_AUTO_REGISTER_FORMS', true), FILTER_VALIDATE_BOOL),
    'pixel_ui_enabled' => filter_var(env('FORMS_PIXEL_UI_ENABLED', false), FILTER_VALIDATE_BOOL),
    'rate_limit_per_minute' => (int) env('FORMS_RATE_LIMIT_PER_MINUTE', 5),
    'rate_limit_per_hour' => (int) env('FORMS_RATE_LIMIT_PER_HOUR', 10),
    'max_payload_kb' => (int) env('FORMS_MAX_PAYLOAD_KB', 256),
    'max_field_length' => (int) env('FORMS_MAX_FIELD_LENGTH', 10000),
    'webhook_timeout' => (int) env('FORMS_WEBHOOK_TIMEOUT', 10),
    'webhook_response_max_length' => (int) env('FORMS_WEBHOOK_RESPONSE_MAX_LENGTH', 2000),
    'health_reports' => [
        'timeout' => (int) env('FORMS_HEALTH_REPORT_TIMEOUT', 10),
        'connect_timeout' => (int) env('FORMS_HEALTH_REPORT_CONNECT_TIMEOUT', 5),
        'max_response_kb' => (int) env('FORMS_HEALTH_REPORT_MAX_RESPONSE_KB', 1024),
        'frequency_days' => (int) env('FORMS_HEALTH_REPORT_FREQUENCY_DAYS', 7),
        'max_pages' => (int) env('FORMS_HEALTH_REPORT_MAX_PAGES', 40),
        'max_depth' => (int) env('FORMS_HEALTH_REPORT_MAX_DEPTH', 2),
        'crawl_delay_ms' => (int) env('FORMS_HEALTH_REPORT_CRAWL_DELAY_MS', 100),
        'blocked_paths' => ['/admin', '/login', '/logout', '/cart', '/checkout', '/search', '/wp-admin', '/feed', '/tag', '/author'],
    ],

    'pagespeed' => [
        'api_key' => env('GOOGLE_PAGESPEED_API_KEY'),
        'timeout' => (int) env('FORMS_PAGESPEED_TIMEOUT', 90),
        'connect_timeout' => (int) env('FORMS_PAGESPEED_CONNECT_TIMEOUT', 10),
        'max_pages' => (int) env('FORMS_PAGESPEED_MAX_PAGES', 3),
    ],

    'search_opportunities' => [
        'minimum_impressions' => (int) env('FORMS_SEARCH_OPPORTUNITIES_MINIMUM_IMPRESSIONS', 100),
        'minimum_emerging_impressions' => (int) env('FORMS_SEARCH_OPPORTUNITIES_MINIMUM_EMERGING_IMPRESSIONS', 50),
        'maximum_ctr' => (float) env('FORMS_SEARCH_OPPORTUNITIES_MAXIMUM_CTR', 0.02),
        'decline_ratio' => (float) env('FORMS_SEARCH_OPPORTUNITIES_DECLINE_RATIO', 0.30),
        'per_type_limit' => (int) env('FORMS_SEARCH_OPPORTUNITIES_PER_TYPE_LIMIT', 5),
    ],
    'spam' => [
        'threshold' => (int) env('FORMS_SPAM_THRESHOLD', 3),
        'max_links' => (int) env('FORMS_SPAM_MAX_LINKS', 3),
        'long_content_length' => (int) env('FORMS_SPAM_LONG_CONTENT_LENGTH', 4000),
        'empty_content_score' => (int) env('FORMS_SPAM_EMPTY_CONTENT_SCORE', 3),
        'html_link_score' => (int) env('FORMS_SPAM_HTML_LINK_SCORE', 3),
        'automation_phrase_score' => (int) env('FORMS_SPAM_AUTOMATION_PHRASE_SCORE', 3),
        'shortened_link_score' => (int) env('FORMS_SPAM_SHORTENED_LINK_SCORE', 3),
        'mark_link_expiry_days' => (int) env('FORMS_SPAM_MARK_LINK_EXPIRY_DAYS', 30),
        'honeypot_fields' => ['_honeypot', '_sitewell_check'],
        'content_fields' => ['message', 'comments', 'comment', 'enquiry', 'inquiry', 'details'],
        'known_values' => ['robertroori'],
        'automation_phrases' => [
            'xrumer',
            'no longer want to receive future messages',
            'fill the form at',
        ],
        'shortened_link_domains' => ['bit.ly', 'brnd.li', 'cutt.ly', 'psee.io', 'tinyurl.com'],
        'promotional_phrases' => [
            '50% off',
            'free shipping',
            'order yours now',
            'buy now',
            'limited time offer',
        ],
        'unsolicited_phrases' => [
            '1win',
            'business listing',
            'free tool',
            'lead generation tool',
            'traffic booster',
            'web index',
        ],
        'unsolicited_phrase_score' => (int) env('FORMS_SPAM_UNSOLICITED_PHRASE_SCORE', 3),
        'suspicious_company_values' => ['google'],
        'suspicious_phone_pattern' => '/^8\d{10}$/',
        'suspicious_identity_score' => (int) env('FORMS_SPAM_SUSPICIOUS_IDENTITY_SCORE', 3),
    ],
];
