<?php

return [
    'booking_url' => env('MARKETING_BOOKING_URL', 'https://cal.com/ross'),

    'feature_pages' => [
        'website-design-and-management' => [
            'eyebrow' => 'Website design & management',
            'title' => 'A professional website that keeps working after launch',
            'description' => 'Start with a new website or bring the one you already have. Sitewell gives it the ongoing care, monitoring, and improvements it needs to remain useful to your business.',
            'problem_title' => 'A website should not become another neglected job',
            'problem' => 'A typical website project ends on launch day. Forms go unchecked, pages become outdated, and every small change means finding a developer again. Our specialists provide the ongoing care that is normally missing.',
            'outcomes' => [
                ['A website included when you need one', 'We create a professional starting point around your services, audience, and goals.'],
                ['Bring your existing website', 'Keep the website that already represents your business and connect it to Sitewell care.'],
                ['Take your website with you', 'Your website is portable, so staying with Sitewell is about continuing value rather than lock-in.'],
                ['Ongoing improvements', 'Our specialists turn health findings and search opportunities into completed website improvements.'],
            ],
            'steps' => [
                ['Understand', 'We learn how your business wins work and what your website needs to do better.'],
                ['Build or connect', 'We create the website you need or connect the one you already use.'],
                ['Care and improve', 'Sitewell monitors the important details and keeps useful improvements moving.'],
            ],
            'example_title' => 'From an ageing brochure to an active business tool',
            'example' => 'A local service business brings its existing website to Sitewell. Our team connects its forms, establishes a health baseline, identifies the pages that need attention, and begins improving them—without forcing the business to start again.',
            'faqs' => [
                ['Do I need a new website?', 'No. Sitewell can work with an existing website, or include a new website if your current one is no longer the right foundation.'],
                ['Can I take the website with me?', 'Yes. Sitewell websites are portable. We will explain the practical handover details before you get started.'],
                ['Will I lose access to my existing accounts?', 'No. Your domain and connected business accounts remain yours.'],
            ],
        ],
        'website-health-monitoring' => [
            'eyebrow' => 'Website health monitoring',
            'title' => 'Find website problems before customers do',
            'description' => 'Our website and SEO specialists monitor the pages your business depends on, prioritise what matters, and manage the work needed to keep them healthy.',
            'problem_title' => 'Small faults quietly cost trust and enquiries',
            'problem' => 'Broken links, missing page titles, inaccessible content, security warnings, and forms that no longer behave as expected are easy to miss when nobody is checking.',
            'outcomes' => [
                ['Ongoing specialist oversight', 'We revisit important pages so a healthy launch does not become an unhealthy website.'],
                ['Plain-English reports', 'See what we found, why it matters, and what our team is doing about it.'],
                ['Page-level evidence', 'Findings point to the affected page instead of leaving you with a vague health score.'],
                ['Fixes managed for you', 'Our team prepares and carries out the improvements, consulting you when a significant change needs your input.'],
            ],
            'steps' => [
                ['Inspect', 'Our specialists check the important pages, website health, and search essentials.'],
                ['Prioritise', 'We decide which findings matter to customers, search visibility, and your business.'],
                ['Improve', 'Our team completes the agreed work and keeps you informed in plain English.'],
            ],
            'example_title' => 'A useful report, not a wall of warnings',
            'example' => 'Our specialist finds that a key service page has no useful search description and links to an old enquiry page. We explain both issues in the weekly report and manage the work needed to put them right.',
            'faqs' => [
                ['What does Sitewell check?', 'Checks include accessibility, metadata, links, performance, security, technical SEO, and the overall structure of important pages.'],
                ['Will I receive technical reports?', 'The evidence remains available, but the main report is written around business impact and practical next steps.'],
                ['Who makes the changes?', 'Our specialists manage the work for you. We consult you before significant content or business decisions, while routine website care stays off your desk.'],
            ],
        ],
        'forms-and-lead-management' => [
            'eyebrow' => 'Forms & lead management',
            'title' => 'Give every genuine enquiry a dependable next step',
            'description' => 'Connect website forms to one lead inbox, acknowledge the customer promptly, and keep follow-up visible until the enquiry is resolved.',
            'problem_title' => 'An enquiry is only valuable if somebody sees and follows it up',
            'problem' => 'Website forms often rely on a single email notification. Messages can be filtered, forwarded to the wrong person, or forgotten after the first reply.',
            'outcomes' => [
                ['Reliable form capture', 'Submissions remain available in Sitewell even when an inbox rule lets you down.'],
                ['Prompt acknowledgements', 'Customers receive a professional response confirming that their message arrived and what happens next.'],
                ['Spam kept separate', 'Suspicious submissions stay reviewable without overwhelming the genuine lead inbox.'],
                ['A simple follow-up rhythm', 'Statuses, notes, and reminders make the next action visible to the people responsible.'],
            ],
            'steps' => [
                ['Capture', 'A visitor completes a form on your website and Sitewell records the enquiry.'],
                ['Acknowledge', 'The customer receives your chosen reply while the right people are notified.'],
                ['Follow up', 'Your team records notes, updates the lead status, and keeps the next action visible.'],
            ],
            'example_title' => 'Friday enquiry, Monday follow-up',
            'example' => 'A customer requests a quote after the office closes. They immediately receive a helpful acknowledgement, the enquiry waits safely in Sitewell, and the team can see that it needs a call when work resumes.',
            'faqs' => [
                ['Do I need to replace my forms?', 'Sitewell is designed to discover and connect the forms on your website. We will confirm the lightest setup for your site.'],
                ['Are submissions limited?', 'No. Plans include unlimited form submissions, subject to fair-use and spam controls.'],
                ['Can different forms notify different people?', 'Form names, recipients, replies, and connected workflows can be arranged around the way your business handles each type of enquiry.'],
            ],
        ],
        'seo-and-search-growth' => [
            'eyebrow' => 'SEO & search growth',
            'title' => 'Turn real search activity into the next useful improvement',
            'description' => 'Our SEO specialists interpret how your website appears in Google, find commercially useful opportunities, and manage the page improvements most likely to move the business forward.',
            'problem_title' => 'Search data is plentiful; knowing what to do next is harder',
            'problem' => 'Clicks, impressions, and ranking positions do not improve a website by themselves. Businesses need to know which query matters, which page is involved, and what change is worth making.',
            'outcomes' => [
                ['Specialist search analysis', 'We interpret your real Google search activity in the context of your services, locations, and goals.'],
                ['Striking-distance opportunities', 'Surface relevant searches where a useful page is already close to stronger visibility.'],
                ['Page-level improvements', 'Our specialists strengthen the page that needs a clearer answer, better structure, or more useful content.'],
                ['Ongoing management', 'We keep analysis, implementation, and reporting connected instead of treating SEO as a one-off exercise.'],
            ],
            'steps' => [
                ['Understand', 'We learn which services, locations, and types of work matter most to your business.'],
                ['Analyse', 'Our specialists interpret queries, pages, positions, impressions, and commercial relevance.'],
                ['Improve', 'We turn the best opportunity into a stronger page, useful new content, or a clear wider SEO action.'],
            ],
            'example_title' => 'A ranking becomes an action',
            'example' => 'A service page is appearing near page one for a commercially useful local search. Our SEO specialist identifies why the page is underperforming, adds the missing section, and strengthens its relevance to the service and location.',
            'faqs' => [
                ['Do you guarantee rankings?', 'No responsible specialist can guarantee a particular search position. We provide evidence-led priorities, expert implementation, and a dependable improvement process.'],
                ['How quickly will SEO improve?', 'Timing depends on the website, market, competition, and the work approved. Sitewell makes progress visible without pretending search growth is instant.'],
                ['Which plan includes specialist SEO management?', 'Search analysis, opportunity planning, and managed content improvements are included from the Growth plan.'],
            ],
        ],
        'content-planning-and-generation' => [
            'eyebrow' => 'SEO content management',
            'title' => 'Useful content, planned and written by specialists',
            'description' => 'Our SEO specialists use website findings, search activity, and your commercial priorities to plan and produce the page or improvement worth doing next.',
            'problem_title' => 'More content is not the same as better content',
            'problem' => 'A stream of generic articles can consume time without helping customers or search visibility. Useful content starts with a real question, gap, service, or existing page that deserves attention.',
            'outcomes' => [
                ['Evidence-led planning', 'Our team grounds decisions in website findings, search performance, and commercial relevance.'],
                ['The right type of content', 'We improve an existing page, create a focused landing page, or write a useful article according to the opportunity.'],
                ['Your priorities included', 'Tell us which services, locations, questions, or pages matter most to the business.'],
                ['Specialist writing and implementation', 'We handle the research, writing, optimisation, and website work for you.'],
            ],
            'steps' => [
                ['Plan', 'Our specialist identifies the strongest opportunity or starts with a priority you have shared.'],
                ['Write', 'We research and write the content around your business, audience, and existing website.'],
                ['Implement', 'Our team adds the improvement to your website and keeps its performance under review.'],
            ],
            'example_title' => 'Improve the page that is already earning attention',
            'example' => 'Search data shows an existing service page appearing for a valuable question. Instead of producing an unrelated blog post, our SEO specialist writes and adds the missing section to the page, then monitors how its visibility develops.',
            'faqs' => [
                ['What can your team create?', 'Work can include service and location landing pages, articles, and focused improvements to pages already on your website.'],
                ['Who writes the content?', 'Our SEO specialists manage the research, structure, writing, optimisation, and implementation. We consult you when we need business knowledge or approval.'],
                ['Can I request a specific topic?', 'Yes. Share a service, location, question, or priority and our team will assess the best way to use it.'],
            ],
        ],
        'google-business-profile' => [
            'eyebrow' => 'Google Business Profile',
            'title' => 'Keep your website and local presence working together',
            'description' => 'Our specialists look after your Google Business Profile alongside your website, keeping its information current and your local presence active.',
            'problem_title' => 'A neglected profile can undermine a well-cared-for website',
            'problem' => 'Outdated details, unanswered reviews, and long gaps between updates can make a healthy business appear inactive. The work is small, but it is easily pushed aside.',
            'outcomes' => [
                ['Profile health management', 'We find and resolve incomplete or inconsistent business information.'],
                ['Specialist recommendations', 'Our team identifies the changes most likely to improve trust and local visibility.'],
                ['Google posts', 'We prepare relevant updates when the business has something useful to share.'],
                ['Customer review replies', 'Our team prepares thoughtful, consistent responses in your business’s voice.'],
            ],
            'steps' => [
                ['Understand', 'We confirm the locations, services, and business information that need to be represented.'],
                ['Manage', 'Our specialists monitor profile health, reviews, and opportunities for useful updates.'],
                ['Improve', 'We prepare and manage the agreed posts, replies, and profile changes for you.'],
            ],
            'example_title' => 'A good review receives a thoughtful response',
            'example' => 'A new customer review appears. Our specialist prepares a concise, thoughtful response in the context of the review and your business, without leaving you to start from a blank page.',
            'faqs' => [
                ['Will I stay in control of what is published?', 'Yes. Our specialists handle the ongoing work and consult you where an update or response needs your approval.'],
                ['Can Sitewell help me get more reviews?', 'The current product helps you monitor and respond to reviews. It does not promise or manufacture customer reviews.'],
                ['Which plan includes this?', 'Google Business Profile management is included in the Complete plan.'],
            ],
        ],
    ],

    'clients' => [
        [
            'name' => 'Luxury Casa Rentals',
            'url' => 'https://luxurycasarentals.com',
            'sector' => 'Luxury travel & experiences',
            'description' => 'A destination-led website bringing together luxury accommodation and bookable experiences in Tenerife.',
            'focus' => ['Accommodation and experience discovery', 'Enquiry journeys', 'Search-focused destination content'],
        ],
        [
            'name' => 'Casa Amore Tenerife',
            'url' => 'https://casaamoretenerife.com',
            'sector' => 'Luxury hospitality',
            'description' => 'A content-rich website presenting a fully serviced luxury villa, its amenities, occasions, and booking journey.',
            'focus' => ['Premium brand presentation', 'Detailed service and occasion pages', 'Availability and booking calls to action'],
        ],
        [
            'name' => 'VVIP Events Zante',
            'url' => 'https://vvipeventszante.com',
            'sector' => 'Events & ticketing',
            'description' => 'A high-traffic seasonal events website covering tickets, packages, event information, guides, and booking management.',
            'focus' => ['Event and package discovery', 'Ticket sales journeys', 'Seasonal content and search visibility'],
        ],
        [
            'name' => 'Northern Prep Squad',
            'url' => 'https://northernprepsquad.co.uk',
            'sector' => 'Training & talent management',
            'description' => 'A specialist website explaining professional training, industry opportunities, events, and management for young performers.',
            'focus' => ['Clear programme structure', 'Audience-specific information', 'Enquiries and member access'],
        ],
    ],

    'industries' => [
        'travel-and-hospitality' => [
            'eyebrow' => 'Travel & hospitality',
            'title' => 'Turn inspiration into confident enquiries and bookings',
            'description' => 'We manage content-rich travel and hospitality websites where brand presentation, detailed information, search visibility, and a dependable booking journey all need to work together.',
            'challenges' => [
                ['Many reasons to visit', 'Accommodation, amenities, occasions, locations, and experiences need a clear structure rather than competing for attention.'],
                ['High-consideration decisions', 'Guests need enough detail and reassurance to move from browsing to checking availability.'],
                ['Seasonal search demand', 'Pages and content must stay useful as destinations, dates, and customer priorities change.'],
            ],
            'management' => [
                'Website health and booking-journey oversight',
                'Search-led accommodation, occasion, and destination pages',
                'Content improvements grounded in real search performance',
                'Form, enquiry, and customer-response management',
            ],
            'clients' => ['Luxury Casa Rentals', 'Casa Amore Tenerife'],
        ],
        'events-and-experiences' => [
            'eyebrow' => 'Events & experiences',
            'title' => 'Keep fast-moving event websites clear, visible, and ready to sell',
            'description' => 'Our specialists manage the website and search work behind ticketed events, seasonal programmes, packages, and customer information.',
            'challenges' => [
                ['Time-sensitive information', 'Dates, availability, line-ups, and packages need to remain accurate across a busy website.'],
                ['Complex customer journeys', 'Visitors must move easily between discovery, comparison, FAQs, booking, and account management.'],
                ['Seasonal visibility', 'Search demand builds and changes quickly, so priority pages cannot be left untouched between launches.'],
            ],
            'management' => [
                'Event, package, and booking-page management',
                'Seasonal SEO planning and implementation',
                'Customer enquiry and form oversight',
                'Website health monitoring during high-demand periods',
            ],
            'clients' => ['VVIP Events Zante'],
        ],
        'training-and-professional-services' => [
            'eyebrow' => 'Training & professional services',
            'title' => 'Explain specialist services clearly and earn the right enquiries',
            'description' => 'We help expert-led organisations turn complex programmes, services, and professional knowledge into a website people can understand and trust.',
            'challenges' => [
                ['Different audiences and needs', 'Prospective clients, existing members, parents, partners, and professionals may all need different information.'],
                ['Expertise can be difficult to explain', 'Specialist services need clear structure and language without losing their depth or credibility.'],
                ['Trust before enquiry', 'Visitors need evidence, expectations, and practical answers before they are ready to make contact.'],
            ],
            'management' => [
                'Service and programme page planning',
                'Search-led content written around genuine audience questions',
                'Website health and enquiry oversight',
                'Ongoing updates as services and opportunities change',
            ],
            'clients' => ['Northern Prep Squad'],
        ],
    ],
];
