<?php

return [
    'booking_url' => env('MARKETING_BOOKING_URL', 'https://cal.com/ross'),
    'contact_website_id' => env('MARKETING_CONTACT_WEBSITE_ID'),

    'landing_pages' => [
        'website-management-services' => [
            'seo_title' => 'Website management services UK',
            'meta_description' => 'Ongoing website management for UK businesses, including website health, content, forms, SEO improvements and specialist support.',
            'eyebrow' => 'Website management services',
            'title' => 'Your business website, managed by specialists',
            'description' => 'Sitewell gives growing UK businesses one dependable team to monitor, maintain and improve their website after launch.',
            'problem_title' => 'A business website is too important to be nobody’s job',
            'problem' => 'Websites gradually fall behind when updates, health checks, content, enquiries and search performance belong to different people—or to whoever has time. Small problems remain unnoticed and useful improvements never quite reach the top of the list.',
            'benefits' => [
                ['One accountable team', 'Website health, content, forms and search improvements are managed together rather than passed between suppliers.'],
                ['Ongoing attention', 'Regular monitoring and clear priorities keep the website useful long after its original launch.'],
                ['Practical improvements', 'Our specialists turn evidence into completed work instead of leaving you with another report to interpret.'],
                ['A website you still own', 'Bring the site you already use or have us create one, with a clear and portable foundation.'],
            ],
            'service_title' => 'More than updates and maintenance',
            'service_description' => 'Sitewell looks after the complete role your website plays in the business, from staying healthy to earning and handling better enquiries.',
            'services' => [
                ['Website health monitoring', 'Regular checks across important pages, links, accessibility, security, search essentials and form delivery.'],
                ['Content and page changes', 'Existing pages are kept accurate and useful, while worthwhile new content is planned and prepared.'],
                ['Search performance', 'Search Console activity and SEO opportunities inform the pages our specialists improve next.'],
                ['Forms and enquiries', 'Genuine submissions stay visible, spam stays separate and follow-up remains easier to manage.'],
                ['Specialist support', 'You have a team that understands the website and can discuss decisions without unnecessary jargon.'],
                ['Clear reporting', 'See what was found, what matters and what has been completed in plain English.'],
            ],
            'steps' => [
                ['Review', 'We start with your existing website, business priorities and the areas that need attention.'],
                ['Connect', 'We agree the right way to monitor and manage the website without disrupting what already works.'],
                ['Improve', 'Our specialists keep health, content, search and enquiry improvements moving over time.'],
            ],
            'difference_title' => 'Management means taking responsibility for progress',
            'difference' => 'Basic maintenance keeps software updated. Sitewell goes further by connecting website health, search visibility, content and enquiries to a managed improvement process. You retain oversight, while our specialists take responsibility for moving the useful work forward.',
            'faqs' => [
                ['What does a website management service include?', 'Sitewell can manage website health monitoring, content changes, forms and enquiries, search performance, SEO improvements and ongoing specialist support. The exact work depends on your plan and website setup.'],
                ['Can you manage a website you did not build?', 'Yes. You can bring an existing website to Sitewell. We review its current platform and agree the safest way to connect and manage it.'],
                ['Do I have to move my website hosting?', 'Not necessarily. The right setup depends on how your website is built. We can discuss Pixel, WordPress and repository-based connection options before making changes.'],
                ['Will I still own my website?', 'Yes. Your domain and connected business accounts remain yours, and we explain website portability and handover arrangements clearly.'],
            ],
            'related' => [
                ['small-business-website-support', 'Website support for small businesses', 'Get dependable help with changes, faults and the everyday questions that hold website work up.'],
                ['managed-seo-services', 'Managed SEO services', 'Turn search performance into page improvements and useful new content.'],
                ['improve-my-website', 'Improve an existing website', 'Start with what you already have and make the strongest parts work harder.'],
            ],
        ],
        'small-business-website-support' => [
            'seo_title' => 'Small business website support',
            'meta_description' => 'Dependable UK website support for small businesses that need help with updates, problems, content, forms and ongoing improvements.',
            'eyebrow' => 'Small business website support',
            'title' => 'Website support without chasing three different suppliers',
            'description' => 'Get a UK-based specialist team that knows your website, answers practical questions and manages the work needed to keep it moving.',
            'problem_title' => 'Small website jobs become large distractions',
            'problem' => 'A broken form, outdated service page or unexplained search decline can consume hours when nobody clearly owns the answer. Hosting companies, designers and SEO providers may each cover one part, leaving the business to coordinate the rest.',
            'benefits' => [
                ['People who know the context', 'Your support team can see the website, recent findings and active priorities before recommending a next step.'],
                ['Help beyond emergencies', 'Support includes planned improvements as well as faults, questions and routine website changes.'],
                ['Clear decisions', 'We explain the available options and business impact without asking you to translate technical language.'],
                ['Continuity after launch', 'The website keeps receiving attention instead of becoming an unsupported project once it goes live.'],
            ],
            'service_title' => 'Support for the website as a working business tool',
            'service_description' => 'We combine responsive help with regular oversight, so support is not limited to waiting for something to break.',
            'services' => [
                ['Content updates', 'Keep services, team information, calls to action and important customer details current.'],
                ['Problem investigation', 'Find the cause of broken pages, links, forms and other visible website issues.'],
                ['Health oversight', 'Regular checks surface technical and usability problems before they are easily missed.'],
                ['Form support', 'Keep website enquiries reaching the right people and remaining available for follow-up.'],
                ['Search guidance', 'Understand changes in visibility and identify which page or opportunity deserves attention.'],
                ['Planning calls', 'Discuss priorities with a specialist who can connect the website work to business goals.'],
            ],
            'steps' => [
                ['Understand', 'We learn how the website is built, what it needs to achieve and where support has been difficult.'],
                ['Prioritise', 'Urgent faults and high-value improvements are separated from work that can sensibly wait.'],
                ['Support', 'Our team handles agreed changes and keeps the website under active review.'],
            ],
            'difference_title' => 'Support should reduce work, not create another queue to manage',
            'difference' => 'Sitewell is designed for owners and teams who do not want to become their own website manager. We keep the evidence, conversation and improvement work connected, giving you one place to understand what is happening and one specialist team to move it forward.',
            'faqs' => [
                ['Can you support my existing website?', 'Yes. We first review the website and its platform, then recommend the most appropriate way to connect it to Sitewell.'],
                ['What kinds of website changes can I request?', 'Requests can include updates to existing pages, new landing pages or articles, form improvements and other changes that fit your website and plan.'],
                ['Is this only WordPress website support?', 'No. Sitewell can work through the Sitewell Pixel, a WordPress connection or a GitHub repository, depending on how the website is built.'],
                ['Can I speak to someone about the website?', 'Yes. Specialist calls are available to discuss findings, connection options and the improvements worth prioritising.'],
            ],
            'related' => [
                ['website-management-services', 'Website management services', 'Move from reactive requests to ongoing care across the whole website.'],
                ['improve-my-website', 'Help improving your website', 'Identify what deserves changing instead of starting with an unfocused redesign.'],
                ['website-lead-generation', 'Get more website leads', 'Improve the journey from arriving on a page to making a genuine enquiry.'],
            ],
        ],
        'managed-seo-services' => [
            'seo_title' => 'Managed SEO services UK',
            'meta_description' => 'Managed SEO for UK businesses, connecting Google Search Console, commercial opportunities, stronger pages and specialist implementation.',
            'eyebrow' => 'Managed SEO services',
            'title' => 'SEO analysis that becomes useful website work',
            'description' => 'Sitewell’s SEO specialists interpret real search performance, find commercially relevant opportunities and manage the page improvements worth making.',
            'problem_title' => 'More SEO data does not automatically create growth',
            'problem' => 'Ranking reports and dashboards can describe what happened without deciding what to do next. Progress needs somebody to connect searches with the right page, understand commercial relevance and carry a considered improvement through to the website.',
            'benefits' => [
                ['Evidence-led priorities', 'Search Console data, website findings and commercial context shape the work rather than generic keyword lists.'],
                ['Page-level decisions', 'Every worthwhile opportunity is connected to the page that needs strengthening or the gap that needs filling.'],
                ['Specialist implementation', 'Recommendations move into reviewable content and website improvements instead of stopping at a report.'],
                ['Ongoing interpretation', 'Performance is revisited over time so new work responds to changing searches and results.'],
            ],
            'service_title' => 'Search performance, content and implementation in one service',
            'service_description' => 'Our managed SEO work focuses on earning relevant visibility and turning it into stronger customer journeys—not chasing traffic without a business purpose.',
            'services' => [
                ['Search Console analysis', 'Understand real queries, clicks, impressions, ranking pages and changes over time.'],
                ['Commercial opportunities', 'Prioritise searches that align with valuable services, locations and customer needs.'],
                ['Existing page improvements', 'Strengthen useful pages with clearer answers, structure, relevance and calls to action.'],
                ['New landing pages', 'Create focused pages where a genuine service, location or audience gap exists.'],
                ['Content planning', 'Choose articles and supporting content because they contribute to a wider search goal.'],
                ['Website health', 'Keep technical and on-page fundamentals from undermining otherwise useful SEO work.'],
            ],
            'steps' => [
                ['Connect', 'We connect matching Google Search Console data and establish the website’s current search position.'],
                ['Choose', 'Our specialist identifies the most commercially useful page or content opportunity to pursue next.'],
                ['Implement', 'We prepare the improvement, manage its website delivery and continue monitoring performance.'],
            ],
            'difference_title' => 'The objective is better business, not simply more traffic',
            'difference' => 'Sitewell considers whether a search fits your services, whether the ranking page answers it well and whether improving that page can support a valuable customer action. Traffic is useful when it brings the right people to a website prepared to help them.',
            'faqs' => [
                ['What is a managed SEO service?', 'A managed SEO service combines analysis, prioritisation, content and implementation. Sitewell’s specialists identify opportunities and manage the agreed website improvements rather than only supplying recommendations.'],
                ['Do you guarantee Google rankings?', 'No responsible SEO provider can guarantee a particular position. We provide evidence-led priorities, specialist implementation and clear reporting on progress.'],
                ['Do I need Google Search Console?', 'Connecting Search Console gives Sitewell first-party information about the searches where your website appears. We can help you connect a property that matches your website.'],
                ['Which Sitewell package includes managed SEO?', 'Growth includes search performance interpretation, opportunity planning, page improvements and ongoing content management.'],
            ],
            'related' => [
                ['website-management-services', 'Managed website services', 'Keep SEO connected to the health, content and day-to-day management of the website.'],
                ['website-lead-generation', 'Turn traffic into website leads', 'Make stronger visibility useful by improving the customer journey and enquiry path.'],
                ['improve-my-website', 'Improve your existing website', 'Combine search evidence with the wider changes that make a website more effective.'],
            ],
        ],
        'website-lead-generation' => [
            'seo_title' => 'Get more website leads',
            'meta_description' => 'Improve your website’s ability to generate and handle enquiries with clearer pages, dependable forms and evidence-led ongoing management.',
            'eyebrow' => 'Website lead generation',
            'title' => 'Help more of the right visitors become genuine enquiries',
            'description' => 'Sitewell improves the pages, calls to action, forms and follow-up process that turn website attention into visible business opportunities.',
            'problem_title' => 'Traffic can arrive without creating enough enquiries',
            'problem' => 'A visitor may find the website but still leave because the service is unclear, the page does not answer their concern, trust is missing or the next step feels difficult. Even a completed form creates little value if the message is lost or follow-up is forgotten.',
            'benefits' => [
                ['Clearer service journeys', 'Important pages help the right visitor understand the offer, evidence and next step more quickly.'],
                ['Dependable enquiry forms', 'Submissions remain visible, spam stays separate and delivery does not depend on a single inbox message.'],
                ['Better follow-up visibility', 'Lead status, notes and reminders make it easier to see which genuine enquiry needs attention.'],
                ['Search with intent', 'SEO work focuses on commercially relevant searches rather than treating every visit as equally valuable.'],
            ],
            'service_title' => 'Improve the complete path from search to follow-up',
            'service_description' => 'Lead generation is not one button or form. We look at how the right customer arrives, decides to trust the business, takes action and receives a dependable response.',
            'services' => [
                ['Service page clarity', 'Explain who the service is for, what happens and why the business is a credible choice.'],
                ['Calls to action', 'Give visitors an appropriate next step at the moments when they are ready to act.'],
                ['Form experience', 'Keep forms focused, understandable and dependable across mobile and desktop journeys.'],
                ['Submission management', 'Store genuine enquiries in one lead inbox with status, notes and follow-up reminders.'],
                ['Search intent', 'Strengthen pages around relevant customer needs rather than broad, low-value traffic.'],
                ['Ongoing improvement', 'Use website findings and real activity to decide which part of the journey deserves attention next.'],
            ],
            'steps' => [
                ['Find the friction', 'We review key pages, forms and customer journeys to identify where useful attention is being lost.'],
                ['Improve the journey', 'Our specialists clarify the page, strengthen the next step and resolve avoidable form problems.'],
                ['Keep leads visible', 'Submissions and follow-up remain easier to manage while website performance continues to be reviewed.'],
            ],
            'difference_title' => 'A lead is only useful when the whole journey works',
            'difference' => 'Sitewell connects search visibility, page quality, form delivery and follow-up instead of optimising each in isolation. That creates a more dependable path for potential customers and a clearer process for the people responsible for responding.',
            'faqs' => [
                ['How can I get more leads from my website?', 'Start by checking whether the right visitors can find relevant pages, understand the offer, trust the business and complete a dependable next step. Sitewell helps identify and manage improvements across that complete journey.'],
                ['Do I need more website traffic first?', 'Not always. Improving the experience for existing relevant visitors can be more valuable than attracting larger volumes of poorly matched traffic.'],
                ['Can Sitewell manage my existing contact forms?', 'Sitewell can connect compatible website forms to a managed lead inbox with spam handling, notifications, notes, status and follow-up reminders.'],
                ['Will you change the website without approval?', 'We keep significant content and business decisions reviewable. The appropriate approval process depends on the type of improvement and connection method.'],
            ],
            'related' => [
                ['managed-seo-services', 'Bring in more relevant search traffic', 'Use managed SEO to connect valuable searches with stronger service pages.'],
                ['improve-my-website', 'Improve the wider website', 'Resolve the content, health and usability issues that influence customer confidence.'],
                ['small-business-website-support', 'Get ongoing website support', 'Keep forms, pages and customer journeys working after the first improvement.'],
            ],
        ],
        'improve-my-website' => [
            'seo_title' => 'Improve my business website',
            'meta_description' => 'Improve your existing business website with clearer priorities across health, content, search visibility, forms and customer journeys.',
            'eyebrow' => 'Improve my website',
            'title' => 'Make the website you already have work harder',
            'description' => 'You may not need another redesign. Sitewell finds what is holding your current website back and manages the improvements most likely to matter.',
            'problem_title' => 'Knowing the website could be better is not a useful plan',
            'problem' => 'An ageing design, weak enquiries, falling traffic or a collection of small faults can all create the feeling that a website needs improving. Starting everywhere at once usually means spending money without deciding which change will make the greatest difference.',
            'benefits' => [
                ['A clear starting point', 'Website health, search activity, content and enquiry journeys reveal what deserves attention first.'],
                ['Keep what still works', 'Useful pages, existing visibility and familiar customer journeys do not need to be discarded unnecessarily.'],
                ['Prioritised changes', 'Improvements are ordered by business impact rather than by whichever issue is easiest to spot.'],
                ['Ongoing progress', 'The website continues improving after the first fixes instead of drifting back into neglect.'],
            ],
            'service_title' => 'Improve the weak points without losing the strong ones',
            'service_description' => 'Our specialists examine the website as a connected whole and choose practical work across the areas affecting trust, visibility and enquiries.',
            'services' => [
                ['Website health', 'Resolve broken links, missing essentials, accessibility gaps and other issues affecting important pages.'],
                ['Page content', 'Clarify services, strengthen useful answers and keep important business information current.'],
                ['Search visibility', 'Use real search performance and relevant opportunities to guide stronger pages and content.'],
                ['Customer journeys', 'Make it easier for the right visitor to understand the offer and choose an appropriate next step.'],
                ['Forms and follow-up', 'Keep genuine enquiries dependable and visible after the visitor presses submit.'],
                ['Design or rebuild decisions', 'Recommend a new foundation only when improving the current one is no longer the sensible route.'],
            ],
            'steps' => [
                ['Assess', 'Start with the existing website and gather evidence across health, search, content and enquiry journeys.'],
                ['Agree', 'Discuss the findings with a specialist and choose the improvements worth prioritising.'],
                ['Improve', 'Sitewell prepares and manages the work, then keeps the website’s progress under review.'],
            ],
            'difference_title' => 'A redesign is an option, not the automatic answer',
            'difference' => 'Sitewell can work with the website you already have, connect it to ongoing care and improve it methodically. If a new website is genuinely the better foundation, we can create one as part of the service and explain the practical reasons clearly.',
            'faqs' => [
                ['Where should I start when improving my website?', 'Begin with evidence: check important pages, technical health, search visibility, customer journeys and form delivery. This helps separate urgent problems from lower-value cosmetic changes.'],
                ['Do I need a complete website redesign?', 'Not necessarily. Many websites can improve through focused health, content, search and enquiry changes. We recommend a new website only when the existing foundation is no longer sensible to develop.'],
                ['Can you improve a website built by somebody else?', 'Yes. We review the current setup and agree whether Pixel, WordPress or repository-based management is the appropriate connection method.'],
                ['How do I find out what is wrong with my website?', 'Enter your website on the Sitewell Get started page. We will review publicly visible signals and show an initial set of findings before you decide what to do next.'],
            ],
            'related' => [
                ['website-management-services', 'Keep the website managed', 'Turn the first set of improvements into dependable ongoing website care.'],
                ['managed-seo-services', 'Improve search visibility', 'Use real search activity to prioritise stronger pages and useful new content.'],
                ['website-lead-generation', 'Earn more website enquiries', 'Improve the parts of the customer journey that turn interest into action.'],
            ],
        ],
    ],

    'feature_pages' => [
        'website-design-and-management' => [
            'eyebrow' => 'Website design & management',
            'title' => 'A professional website that keeps working after launch',
            'description' => 'Start with a new website or bring the one you already have. Sitewell gives it the ongoing care, monitoring, and improvements it needs to remain useful to your business.',
            'problem_title' => 'A website should not become another neglected job',
            'problem' => 'A typical website project ends on launch day. Forms go unchecked, pages become outdated, and every small change means finding a developer again. Our specialists provide the ongoing care that is normally missing.',
            'outcomes' => [
                ['A website included when you need one', 'We create a professional starting point around your services, audience, and goals.'],
                ['Bring your existing website', 'Keep the website that already represents your business and connect it to Sitewell care.'],
                ['Take your website with you', 'Your website is portable, so staying with Sitewell is about continuing value rather than lock-in.'],
                ['Ongoing improvements', 'Our specialists turn health findings and search opportunities into completed website improvements.'],
            ],
            'steps' => [
                ['Understand', 'We learn how your business wins work and what your website needs to do better.'],
                ['Build or connect', 'We create the website you need or connect the one you already use.'],
                ['Care and improve', 'Sitewell monitors the important details and keeps useful improvements moving.'],
            ],
            'example_title' => 'From an ageing brochure to an active business tool',
            'example' => 'A local service business brings its existing website to Sitewell. Our team connects its forms, establishes a health baseline, identifies the pages that need attention, and begins improving them—without forcing the business to start again.',
            'faqs' => [
                ['Do I need a new website?', 'No. Sitewell can work with an existing website, or include a new website if your current one is no longer the right foundation.'],
                ['Can I take the website with me?', 'Yes. Sitewell websites are portable. We will explain the practical handover details before you get started.'],
                ['Will I lose access to my existing accounts?', 'No. Your domain and connected business accounts remain yours.'],
            ],
        ],
        'website-health-monitoring' => [
            'eyebrow' => 'Website health monitoring',
            'title' => 'Find website problems before customers do',
            'description' => 'Our website and SEO specialists monitor the pages your business depends on, prioritise what matters, and manage the work needed to keep them healthy.',
            'problem_title' => 'Small faults quietly cost trust and enquiries',
            'problem' => 'Broken links, missing page titles, inaccessible content, security warnings, and forms that no longer behave as expected are easy to miss when nobody is checking.',
            'outcomes' => [
                ['Ongoing specialist oversight', 'We revisit important pages so a healthy launch does not become an unhealthy website.'],
                ['Plain-English reports', 'See what we found, why it matters, and what our team is doing about it.'],
                ['Page-level evidence', 'Findings point to the affected page instead of leaving you with a vague health score.'],
                ['Fixes managed for you', 'Our team prepares and carries out the improvements, consulting you when a significant change needs your input.'],
            ],
            'steps' => [
                ['Inspect', 'Our specialists check the important pages, website health, and search essentials.'],
                ['Prioritise', 'We decide which findings matter to customers, search visibility, and your business.'],
                ['Improve', 'Our team completes the agreed work and keeps you informed in plain English.'],
            ],
            'example_title' => 'A useful report, not a wall of warnings',
            'example' => 'Our specialist finds that a key service page has no useful search description and links to an old enquiry page. We explain both issues in the weekly report and manage the work needed to put them right.',
            'faqs' => [
                ['What does Sitewell check?', 'Checks include accessibility, metadata, links, performance, security, technical SEO, and the overall structure of important pages.'],
                ['Will I receive technical reports?', 'The evidence remains available, but the main report is written around business impact and practical next steps.'],
                ['Who makes the changes?', 'Our specialists manage the work for you. We consult you before significant content or business decisions, while routine website care stays off your desk.'],
            ],
        ],
        'forms-and-lead-management' => [
            'eyebrow' => 'Forms & lead management',
            'title' => 'Give every genuine enquiry a dependable next step',
            'description' => 'Connect website forms to one lead inbox, acknowledge the customer promptly, and keep follow-up visible until the enquiry is resolved.',
            'problem_title' => 'An enquiry is only valuable if somebody sees and follows it up',
            'problem' => 'Website forms often rely on a single email notification. Messages can be filtered, forwarded to the wrong person, or forgotten after the first reply.',
            'outcomes' => [
                ['Reliable form capture', 'Submissions remain available in Sitewell even when an inbox rule lets you down.'],
                ['Prompt acknowledgements', 'Customers receive a professional response confirming that their message arrived and what happens next.'],
                ['Spam kept separate', 'Suspicious submissions stay reviewable without overwhelming the genuine lead inbox.'],
                ['A simple follow-up rhythm', 'Statuses, notes, and reminders make the next action visible to the people responsible.'],
            ],
            'steps' => [
                ['Capture', 'A visitor completes a form on your website and Sitewell records the enquiry.'],
                ['Acknowledge', 'The customer receives your chosen reply while the right people are notified.'],
                ['Follow up', 'Your team records notes, updates the lead status, and keeps the next action visible.'],
            ],
            'example_title' => 'Friday enquiry, Monday follow-up',
            'example' => 'A customer requests a quote after the office closes. They immediately receive a helpful acknowledgement, the enquiry waits safely in Sitewell, and the team can see that it needs a call when work resumes.',
            'faqs' => [
                ['Do I need to replace my forms?', 'Sitewell is designed to discover and connect the forms on your website. We will confirm the lightest setup for your site.'],
                ['Are submissions limited?', 'No. Plans include unlimited form submissions, subject to fair-use and spam controls.'],
                ['Can different forms notify different people?', 'Form names, recipients, replies, and connected workflows can be arranged around the way your business handles each type of enquiry.'],
            ],
        ],
        'seo-and-search-growth' => [
            'eyebrow' => 'SEO & search growth',
            'title' => 'Turn real search activity into the next useful improvement',
            'description' => 'Our SEO specialists interpret how your website appears in Google, find commercially useful opportunities, and manage the page improvements most likely to move the business forward.',
            'problem_title' => 'Search data is plentiful; knowing what to do next is harder',
            'problem' => 'Clicks, impressions, and ranking positions do not improve a website by themselves. Businesses need to know which query matters, which page is involved, and what change is worth making.',
            'outcomes' => [
                ['Specialist search analysis', 'We interpret your real Google search activity in the context of your services, locations, and goals.'],
                ['Striking-distance opportunities', 'Surface relevant searches where a useful page is already close to stronger visibility.'],
                ['Page-level improvements', 'Our specialists strengthen the page that needs a clearer answer, better structure, or more useful content.'],
                ['Ongoing management', 'We keep analysis, implementation, and reporting connected instead of treating SEO as a one-off exercise.'],
            ],
            'steps' => [
                ['Understand', 'We learn which services, locations, and types of work matter most to your business.'],
                ['Analyse', 'Our specialists interpret queries, pages, positions, impressions, and commercial relevance.'],
                ['Improve', 'We turn the best opportunity into a stronger page, useful new content, or a clear wider SEO action.'],
            ],
            'example_title' => 'A ranking becomes an action',
            'example' => 'A service page is appearing near page one for a commercially useful local search. Our SEO specialist identifies why the page is underperforming, adds the missing section, and strengthens its relevance to the service and location.',
            'faqs' => [
                ['Do you guarantee rankings?', 'No responsible specialist can guarantee a particular search position. We provide evidence-led priorities, expert implementation, and a dependable improvement process.'],
                ['How quickly will SEO improve?', 'Timing depends on the website, market, competition, and the work approved. Sitewell makes progress visible without pretending search growth is instant.'],
                ['Which plan includes specialist SEO management?', 'Search analysis, opportunity planning, and managed content improvements are included from the Growth plan.'],
            ],
        ],
        'content-planning-and-generation' => [
            'eyebrow' => 'SEO content management',
            'title' => 'Useful content, planned and written by specialists',
            'description' => 'Our SEO specialists use website findings, search activity, and your commercial priorities to plan and produce the page or improvement worth doing next.',
            'problem_title' => 'More content is not the same as better content',
            'problem' => 'A stream of generic articles can consume time without helping customers or search visibility. Useful content starts with a real question, gap, service, or existing page that deserves attention.',
            'outcomes' => [
                ['Evidence-led planning', 'Our team grounds decisions in website findings, search performance, and commercial relevance.'],
                ['The right type of content', 'We improve an existing page, create a focused landing page, or write a useful article according to the opportunity.'],
                ['Your priorities included', 'Tell us which services, locations, questions, or pages matter most to the business.'],
                ['Specialist writing and implementation', 'We handle the research, writing, optimisation, and website work for you.'],
            ],
            'steps' => [
                ['Plan', 'Our specialist identifies the strongest opportunity or starts with a priority you have shared.'],
                ['Write', 'We research and write the content around your business, audience, and existing website.'],
                ['Implement', 'Our team adds the improvement to your website and keeps its performance under review.'],
            ],
            'example_title' => 'Improve the page that is already earning attention',
            'example' => 'Search data shows an existing service page appearing for a valuable question. Instead of producing an unrelated blog post, our SEO specialist writes and adds the missing section to the page, then monitors how its visibility develops.',
            'faqs' => [
                ['What can your team create?', 'Work can include service and location landing pages, articles, and focused improvements to pages already on your website.'],
                ['Who writes the content?', 'Our SEO specialists manage the research, structure, writing, optimisation, and implementation. We consult you when we need business knowledge or approval.'],
                ['Can I request a specific topic?', 'Yes. Share a service, location, question, or priority and our team will assess the best way to use it.'],
            ],
        ],
        'google-business-profile' => [
            'eyebrow' => 'Google Business Profile',
            'title' => 'Keep your website and local presence working together',
            'description' => 'Our specialists look after your Google Business Profile alongside your website, keeping its information current and your local presence active.',
            'problem_title' => 'A neglected profile can undermine a well-cared-for website',
            'problem' => 'Outdated details, unanswered reviews, and long gaps between updates can make a healthy business appear inactive. The work is small, but it is easily pushed aside.',
            'outcomes' => [
                ['Profile health management', 'We find and resolve incomplete or inconsistent business information.'],
                ['Specialist recommendations', 'Our team identifies the changes most likely to improve trust and local visibility.'],
                ['Google posts', 'We prepare relevant updates when the business has something useful to share.'],
                ['Customer review replies', 'Our team prepares thoughtful, consistent responses in your business’s voice.'],
            ],
            'steps' => [
                ['Understand', 'We confirm the locations, services, and business information that need to be represented.'],
                ['Manage', 'Our specialists monitor profile health, reviews, and opportunities for useful updates.'],
                ['Improve', 'We prepare and manage the agreed posts, replies, and profile changes for you.'],
            ],
            'example_title' => 'A good review receives a thoughtful response',
            'example' => 'A new customer review appears. Our specialist prepares a concise, thoughtful response in the context of the review and your business, without leaving you to start from a blank page.',
            'faqs' => [
                ['Will I stay in control of what is published?', 'Yes. Our specialists handle the ongoing work and consult you where an update or response needs your approval.'],
                ['Can Sitewell help me get more reviews?', 'The current product helps you monitor and respond to reviews. It does not promise or manufacture customer reviews.'],
                ['Which plan includes this?', 'Google Business Profile management is included in the Complete plan.'],
            ],
        ],
    ],

    'clients' => [
        [
            'name' => 'Luxury Casa Rentals',
            'url' => 'https://luxurycasarentals.com',
            'sector' => 'Luxury travel & experiences',
            'description' => 'A destination-led website bringing together luxury accommodation and bookable experiences in Tenerife.',
            'focus' => ['Accommodation and experience discovery', 'Enquiry journeys', 'Search-focused destination content'],
        ],
        [
            'name' => 'Casa Amore Tenerife',
            'url' => 'https://casaamoretenerife.com',
            'sector' => 'Luxury hospitality',
            'description' => 'A content-rich website presenting a fully serviced luxury villa, its amenities, occasions, and booking journey.',
            'focus' => ['Premium brand presentation', 'Detailed service and occasion pages', 'Availability and booking calls to action'],
        ],
        [
            'name' => 'VVIP Events Zante',
            'url' => 'https://vvipeventszante.com',
            'sector' => 'Events & ticketing',
            'description' => 'A high-traffic seasonal events website covering tickets, packages, event information, guides, and booking management.',
            'focus' => ['Event and package discovery', 'Ticket sales journeys', 'Seasonal content and search visibility'],
        ],
        [
            'name' => 'Northern Prep Squad',
            'url' => 'https://northernprepsquad.co.uk',
            'sector' => 'Training & talent management',
            'description' => 'A specialist website explaining professional training, industry opportunities, events, and management for young performers.',
            'focus' => ['Clear programme structure', 'Audience-specific information', 'Enquiries and member access'],
        ],
    ],

    'industries' => [
        'travel-and-hospitality' => [
            'eyebrow' => 'Travel & hospitality',
            'title' => 'Turn inspiration into confident enquiries and bookings',
            'description' => 'We manage content-rich travel and hospitality websites where brand presentation, detailed information, search visibility, and a dependable booking journey all need to work together.',
            'challenges' => [
                ['Many reasons to visit', 'Accommodation, amenities, occasions, locations, and experiences need a clear structure rather than competing for attention.'],
                ['High-consideration decisions', 'Guests need enough detail and reassurance to move from browsing to checking availability.'],
                ['Seasonal search demand', 'Pages and content must stay useful as destinations, dates, and customer priorities change.'],
            ],
            'management' => [
                'Website health and booking-journey oversight',
                'Search-led accommodation, occasion, and destination pages',
                'Content improvements grounded in real search performance',
                'Form, enquiry, and customer-response management',
            ],
            'clients' => ['Luxury Casa Rentals', 'Casa Amore Tenerife'],
        ],
        'events-and-experiences' => [
            'eyebrow' => 'Events & experiences',
            'title' => 'Keep fast-moving event websites clear, visible, and ready to sell',
            'description' => 'Our specialists manage the website and search work behind ticketed events, seasonal programmes, packages, and customer information.',
            'challenges' => [
                ['Time-sensitive information', 'Dates, availability, line-ups, and packages need to remain accurate across a busy website.'],
                ['Complex customer journeys', 'Visitors must move easily between discovery, comparison, FAQs, booking, and account management.'],
                ['Seasonal visibility', 'Search demand builds and changes quickly, so priority pages cannot be left untouched between launches.'],
            ],
            'management' => [
                'Event, package, and booking-page management',
                'Seasonal SEO planning and implementation',
                'Customer enquiry and form oversight',
                'Website health monitoring during high-demand periods',
            ],
            'clients' => ['VVIP Events Zante'],
        ],
        'training-and-professional-services' => [
            'eyebrow' => 'Training & professional services',
            'title' => 'Explain specialist services clearly and earn the right enquiries',
            'description' => 'We help expert-led organisations turn complex programmes, services, and professional knowledge into a website people can understand and trust.',
            'challenges' => [
                ['Different audiences and needs', 'Prospective clients, existing members, parents, partners, and professionals may all need different information.'],
                ['Expertise can be difficult to explain', 'Specialist services need clear structure and language without losing their depth or credibility.'],
                ['Trust before enquiry', 'Visitors need evidence, expectations, and practical answers before they are ready to make contact.'],
            ],
            'management' => [
                'Service and programme page planning',
                'Search-led content written around genuine audience questions',
                'Website health and enquiry oversight',
                'Ongoing updates as services and opportunities change',
            ],
            'clients' => ['Northern Prep Squad'],
        ],
    ],
];
