<?php

return [
    // Each entry is an editorial brief, not a location/industry substitution.
    // Existing organic service URLs remain canonical for overlapping intents.
    'pages' => [
        'doncaster' => [
            'path' => 'seo/doncaster',
            'title' => 'SEO Company in Doncaster | Sitewell',
            'description' => 'A Doncaster-based SEO service that does the work. Website improvements, Google ranking tracking and weekly reporting, with no long-term contract.',
            'eyebrow' => 'Doncaster based. Personally managed.',
            'heading' => 'SEO company in Doncaster',
            'promise' => 'Your local SEO team. The work, taken care of.',
            'intro' => 'We audit your website, track your Google rankings and make improvements for you. Speak directly with Ross, a web developer based in Doncaster.',
            'problem_title' => 'A good local business deserves a website that pulls its weight',
            'problem' => 'You know the work you do is good. But when someone in Doncaster searches for your service, your website may not explain it clearly enough — or be easy enough to find. You need someone to work on that, without another job landing on your desk.',
            'priorities' => [
                ['Make your services easier to find', 'Build clear pages around the services you actually offer and the areas you genuinely cover.'],
                ['Help local visitors choose you', 'Improve service details, local context and enquiry routes so people can see whether you are the right fit.'],
                ['Keep the conversation straightforward', 'Discuss priorities with Ross and see the work in your weekly update. No account-manager relay.'],
            ],
            'example_title' => 'For a business serving Doncaster and nearby towns',
            'example' => 'If your homepage is trying to cover every service and location, we can separate the important services, explain your real coverage and improve the route to an enquiry. Useful local pages, not a list of town names copied across your site.',
            'faqs' => [
                ['Are you based in Doncaster?', 'Yes. Ross is a web developer based in Doncaster. Sitewell works with local businesses as well as businesses elsewhere in the UK.'],
                ['Can you help me appear for searches outside Doncaster?', 'Yes, where you genuinely serve those areas. We agree the services and locations that matter, then improve relevant pages without manufacturing thin location pages.'],
            ],
            'related' => ['local', 'managed'],
        ],
        'local' => [
            'path' => 'local-seo',
            'canonical_landing' => 'local-seo-services',
            'title' => 'Local SEO Services, Fully Managed | Sitewell',
            'description' => 'Local SEO for businesses that want more relevant local enquiries. We improve your website, monitor search performance and report on the work each week.',
            'eyebrow' => 'For businesses serving a local area',
            'heading' => 'Local SEO services',
            'promise' => 'Help nearby customers find the right business. Yours.',
            'intro' => 'We improve the pages that explain what you do and where you work, track relevant Google rankings and keep your website moving forward.',
            'problem_title' => 'Being nearby is not enough if your website leaves people guessing',
            'problem' => 'A local customer needs to know you offer the service, cover their area and are worth contacting. Vague service pages and out-of-date details make that harder. We turn those gaps into practical website improvements.',
            'priorities' => [
                ['Show where you actually work', 'Explain your service area with useful local detail, rather than near-identical pages for every postcode.'],
                ['Make each service clear', 'Answer the questions people ask before calling, from the jobs you take on to what happens after an enquiry.'],
                ['Monitor relevant local searches', 'Track selected organic Google rankings by location. These are website rankings, not a Google Maps grid.'],
            ],
            'example_title' => 'For a local service business with one general services page',
            'example' => 'We might create a clearer page for your most important service, add genuine coverage details and improve the contact route on mobile. The aim is to help a nearby customer understand the offer and take the next step.',
            'faqs' => [
                ['Is Google Business Profile management included?', 'Website-focused local SEO is part of the managed SEO work. Hands-on Google Business Profile management, posts and review replies are included in Complete, a higher-priced plan. We will explain which plan fits before you commit.'],
                ['Can you guarantee a place in the Maps results?', 'No. Google controls those results. We can improve relevant website signals and, on Complete, manage your Business Profile, but we do not promise a Maps position.'],
            ],
            'related' => ['doncaster', 'small-business'],
        ],
        'small-business' => [
            'path' => 'small-business-seo',
            'canonical_landing' => 'seo-for-small-businesses',
            'title' => 'SEO for Small Businesses | Sitewell',
            'description' => 'Fully managed SEO for small businesses. Clear monthly pricing, practical website improvements and weekly updates. No long-term contract.',
            'eyebrow' => 'For owners with a business to run',
            'heading' => 'SEO for small businesses',
            'promise' => 'Less on your to-do list. More care for your website.',
            'intro' => 'You do not need another SEO tool to learn. We find what needs attention, improve your pages and keep you informed with a clear weekly update.',
            'problem_title' => 'Your website should not become your second job',
            'problem' => 'There is always another SEO recommendation, another tool and another thing to learn. Meanwhile, your service pages stay the same. Sitewell gives you a person responsible for turning useful findings into completed work.',
            'priorities' => [
                ['Focus on the work that matters first', 'Start with your main services and useful search opportunities, rather than chasing every possible keyword.'],
                ['Keep the monthly cost clear', 'One website, a visible monthly price and no long-term contract. Agree the priorities before the work begins.'],
                ['Stay involved without doing the SEO', 'Bring your knowledge of the business. We handle the website work and ask you when a decision needs your input.'],
            ],
            'example_title' => 'For an owner whose website has not changed in a year',
            'example' => 'We could start by updating your main service page, answering common customer questions and fixing search basics. That gives us a useful foundation to monitor before deciding what to improve next.',
            'faqs' => [
                ['Is my business too small for managed SEO?', 'The fit depends on your services, website and priorities, not a minimum team size. The website check gives us a starting point; a conversation helps establish whether ongoing work makes commercial sense.'],
                ['How much of my time will you need?', 'We need your input on the business, access and initial priorities. After that, we do the routine SEO work and come to you for approvals or information we cannot responsibly invent.'],
            ],
            'related' => ['local', 'managed'],
        ],
        'managed' => [
            'path' => 'managed-seo',
            'canonical_landing' => 'managed-seo-services',
            'title' => 'Fully Managed SEO Services | Sitewell',
            'description' => 'Fully managed SEO that gets implemented. Website audits, content, technical improvements, ranking tracking and clear weekly reporting.',
            'eyebrow' => 'Analysis, implementation and ongoing care',
            'heading' => 'Fully managed SEO',
            'promise' => 'We do not just tell you what to improve. We do the work.',
            'intro' => 'Your website audits, Google ranking tracking, content and technical improvements — managed together, with weekly updates showing what has changed.',
            'problem_title' => 'Recommendations do not improve a website. Implementing them does.',
            'problem' => 'An audit identifies the problems. Then somebody still has to rewrite the page, fix the technical issue and check the result. If that work keeps falling between suppliers, managed SEO should close the gap.',
            'priorities' => [
                ['Move from findings to changes', 'We prioritise the audit findings and search opportunities, then prepare and carry out agreed improvements.'],
                ['Connect content and technical work', 'Improve the page itself, from headings and content to crawl signals and internal links.'],
                ['Know what has been done', 'Weekly reporting connects completed work with audit findings and available search data, with clear next steps.'],
            ],
            'example_title' => 'For a business with an audit waiting to be actioned',
            'example' => 'We review the findings against your current website, choose the most useful fixes and work through them. Content changes remain reviewable, and changes that depend on your platform or another supplier are made explicit.',
            'faqs' => [
                ['What does fully managed actually mean?', 'Sitewell handles the analysis, prioritisation and agreed website improvements. You provide access and business context, and approve changes where needed. We do not simply send you a list and leave implementation to you.'],
                ['Does managed SEO mean unlimited work?', 'No. Work is prioritised within your plan and the capabilities of your website. Growth includes up to one scheduled content improvement per week, prepared for review; it is not a promise of unlimited articles or a complete rebuild every month.'],
            ],
            'related' => ['rankings', 'small-business'],
        ],
        'rankings' => [
            'path' => 'improve-google-rankings',
            'title' => 'Improve Your Google Rankings | Sitewell',
            'description' => 'Find out what may be holding your website back on Google. Sitewell checks your website, improves your pages and monitors search progress.',
            'eyebrow' => 'For websites that should be easier to find',
            'heading' => 'Improve your Google rankings',
            'promise' => 'Find what is holding your website back. Then work on it.',
            'intro' => 'Start with a website check. We identify search essentials that need attention, then offer ongoing SEO work to improve your pages and monitor progress.',
            'problem_title' => '“Why are they above us?” needs a useful answer',
            'problem' => 'A page may be hard for Google to access, unclear about its topic or less useful than competing results. Sometimes the search itself is simply very competitive. We investigate the evidence before choosing what to change.',
            'priorities' => [
                ['Check the foundations', 'Review public crawl and on-page signals first. A good-looking website can still have search basics missing.'],
                ['Use your real search data', 'Once connected, Search Console helps us see which queries and pages already receive impressions and clicks.'],
                ['Improve, then measure', 'Strengthen relevant pages and track selected keywords over time. Report movement honestly, including where there is no improvement yet.'],
            ],
            'example_title' => 'For a service page that gets impressions but few clicks',
            'example' => 'After reviewing Search Console data, we might clarify the page title, strengthen the explanation of the service and improve internal links. We then monitor comparable periods rather than claiming that one change guarantees a higher position.',
            'faqs' => [
                ['Will the initial check show all my Google rankings?', 'No. The first check reviews public website signals. Selected keyword tracking and Search Console analysis are part of the connected service, with the relevant setup and permissions.'],
                ['Can you get me to number one?', 'Nobody can honestly guarantee that. We can improve your website, focus on relevant searches and show you the work and available evidence of progress.'],
            ],
            'related' => ['managed', 'local'],
        ],
    ],
    'faqs' => [
        ['How quickly will rankings improve?', 'SEO takes time. Some website fixes can be made quickly, but search results depend on competition, your starting point and Google. Expect ongoing work and measurement over months, with no promised ranking or deadline.'],
        ['Can you work with my existing website or WordPress?', 'Yes. We review the platform and available access first. Sitewell supports WordPress, the Sitewell Pixel and connected repositories where appropriate. We explain any limits before starting; a new website is not automatically required.'],
        ['Do I need to change website provider?', 'Not necessarily. We can work with your existing setup when it supports the improvements needed. If a restriction requires help from your provider, we will explain that rather than promise access we do not have.'],
        ['How do you access my website?', 'The initial check uses public information only. For managed work, we agree a suitable connection and permissions with you. Never enter a website password into the audit form.'],
        ['What exactly do you change?', 'Depending on the priorities, we improve titles, headings, content, internal links, service pages and technical SEO issues. We agree scope and keep significant content and business decisions reviewable.'],
        ['What if my website has technical problems?', 'We identify the problems we can see and explain what we can fix with the access available. If work needs your hosting provider or a larger development project, we flag it and agree the next step.'],
        ['Is there a contract, setup fee or minimum commitment?', 'There is no setup fee or long-term commitment. You can cancel anytime. The monthly service and its scope are covered by our terms of service.'],
        ['What happens if I cancel? Do I own the work?', 'Your website and completed website work stay with you. Ongoing monitoring and managed work stop when your service ends. We agree practical handover details, including any third-party services, before you get started.'],
        ['Do you guarantee rankings?', 'No. Google controls its results. We promise clear priorities, agreed work and honest reporting, not a specific position, traffic increase or number of enquiries.'],
    ],
];
