<div id="website-panel-business-profile" class="space-y-6" role="tabpanel" aria-labelledby="website-tab-business-profile" data-tab-panel="business-profile" hidden>
    @php($profile = $website->businessProfileConnection)
    @if (! $profile)
        <section class="rounded-lg border border-slate-200 bg-white p-6"><h2 class="text-lg font-semibold text-slate-950">Google Business Profile</h2><p class="mt-2 max-w-2xl text-sm text-slate-600">Connect a managed location for weekly health checks, approval-first changes, generated post drafts, and approval-first review replies.</p><p class="mt-2 max-w-2xl text-sm text-slate-600 italic opacity-50">Integration coming soon...</p>
            {{-- <a href="{{ route('admin.business-profile.connect', $website) }}" class="mt-4 inline-flex rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-800">Connect Google Business Profile</a> --}}
        </section>
    @else
        @if (blank($profile->location_name))
            <section class="rounded-lg border border-amber-200 bg-amber-50 p-5" aria-labelledby="business-profile-location-required">
                <p class="text-xs font-semibold uppercase tracking-widest text-amber-700">Action required</p>
                <h2 id="business-profile-location-required" class="mt-1 font-semibold text-amber-950">Choose the Google location to manage</h2>
                <p class="mt-2 max-w-2xl text-sm text-amber-800">Google is authorised, but no Business Profile location has been selected. Select a location before running health checks, syncing reviews, or generating posts.</p>
                <div class="mt-4 flex flex-wrap gap-2">
                    <a href="{{ route('admin.business-profile.locations', $website) }}" class="rounded-md bg-amber-900 px-3 py-2 text-sm font-semibold text-white hover:bg-amber-950">Select a location</a>
                    <a href="{{ route('admin.business-profile.connect', $website) }}" class="rounded-md border border-amber-300 bg-white px-3 py-2 text-sm font-semibold text-amber-900 hover:bg-amber-100">Reconnect Google</a>
                </div>
            </section>
        @endif
        @if (filled($profile->location_name))
        <section class="rounded-lg border border-slate-200 bg-white">
            <div class="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 p-4"><div><p class="text-xs font-medium uppercase tracking-widest text-slate-500">Connected location</p><h2 class="mt-1 text-lg font-semibold text-slate-950">{{ $profile->location_title ?: 'No location selected' }}</h2><p class="mt-1 text-sm text-slate-600">All posts, replies, and profile edits require explicit approval.</p></div><div class="flex flex-wrap gap-2">@if (filled($profile->location_name))<form method="POST" action="{{ route('admin.business-profile.audits.store', $website) }}">@csrf<button class="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white">Run health check</button></form><form method="POST" action="{{ route('admin.business-profile.reviews.sync', $website) }}">@csrf<button class="rounded-md border border-slate-200 px-3 py-2 text-sm font-medium">Sync reviews</button></form><a href="{{ route('admin.business-profile.locations', $website) }}" class="rounded-md border border-slate-200 px-3 py-2 text-sm font-medium">Change location</a>@endif<a href="{{ route('admin.business-profile.connect', $website) }}" class="rounded-md border border-slate-200 px-3 py-2 text-sm font-medium">Reconnect Google</a></div></div>
            @php($latestAudit = $profile->audits->first())
            <div class="p-4"><h3 class="font-medium text-slate-950">Latest recommendations</h3><div class="mt-3 space-y-3">@forelse ($latestAudit?->recommendations ?? [] as $recommendation)<article class="rounded-lg border border-slate-200 p-3"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-medium text-slate-900">{{ $recommendation->title }}</p><p class="mt-1 text-sm text-slate-600">{{ $recommendation->description }}</p><p class="mt-1 text-xs capitalize text-slate-500">{{ str_replace('_', ' ', $recommendation->status) }}</p></div>@if ($recommendation->status === 'pending')<div class="flex gap-2">@if ($recommendation->field_mask && $recommendation->proposed_value)<form method="POST" action="{{ route('admin.business-profile.recommendations.update', [$website, $recommendation]) }}">@csrf @method('PUT')<button class="rounded-md bg-slate-900 px-3 py-2 text-xs font-medium text-white">Approve & apply</button></form>@endif<form method="POST" action="{{ route('admin.business-profile.recommendations.destroy', [$website, $recommendation]) }}">@csrf @method('DELETE')<button class="rounded-md border px-3 py-2 text-xs font-medium">Dismiss</button></form></div>@endif</div></article>@empty<p class="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">{{ $latestAudit ? 'No changes recommended.' : 'Run the first health check to create recommendations.' }}</p>@endforelse</div></div>
        </section>

        <div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-lg border border-slate-200 bg-white p-4"><h3 class="font-semibold text-slate-950">Generated posts</h3><form method="POST" action="{{ route('admin.business-profile.posts.store', $website) }}" class="mt-3 space-y-2">@csrf<textarea name="topic" rows="2" maxlength="1000" class="w-full rounded-md border border-slate-300 px-3 py-2 text-sm" placeholder="Optional topic or offer details"></textarea><button class="rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white">Generate draft</button></form><div class="mt-4 space-y-3">@foreach ($profile->posts as $post)<article class="rounded-lg border border-slate-200 p-3"><p class="text-xs capitalize text-slate-500">{{ str_replace('_', ' ', $post->status) }}</p>@if ($post->summary)<form method="POST" action="{{ route('admin.business-profile.posts.update', [$website, $post]) }}" class="mt-2 space-y-2">@csrf @method('PUT')<textarea name="summary" rows="5" maxlength="1500" class="w-full rounded-md border px-3 py-2 text-sm">{{ $post->summary }}</textarea><input type="hidden" name="call_to_action_type" value="{{ $post->call_to_action_type }}"><input type="hidden" name="call_to_action_url" value="{{ $post->call_to_action_url }}">@if ($post->status === 'pending_approval')<button class="rounded-md bg-emerald-700 px-3 py-2 text-xs font-medium text-white">Approve & publish</button>@endif</form>@endif</article>@endforeach</div></section>
            <section class="rounded-lg border border-slate-200 bg-white p-4"><h3 class="font-semibold text-slate-950">Customer reviews</h3><p class="mt-1 text-sm text-slate-600">AI drafts are never posted until someone approves them.</p><div class="mt-4 space-y-3">@forelse ($profile->reviews as $review)<article class="rounded-lg border border-slate-200 p-3"><div class="flex justify-between gap-3"><p class="font-medium">{{ $review->reviewer_name ?: 'Customer' }}</p><p class="text-amber-600">{{ str_repeat('★', $review->star_rating) }}</p></div><p class="mt-2 text-sm text-slate-600">{{ $review->comment ?: 'Rating without a written comment.' }}</p>@if ($review->reply_status === 'pending_approval')<form method="POST" action="{{ route('admin.business-profile.reviews.update', [$website, $review]) }}" class="mt-3 space-y-2">@csrf @method('PUT')<textarea name="reply" rows="4" maxlength="1200" class="w-full rounded-md border px-3 py-2 text-sm">{{ $review->suggested_reply }}</textarea><button class="rounded-md bg-emerald-700 px-3 py-2 text-xs font-medium text-white">Approve & reply</button></form>@elseif (in_array($review->reply_status, ['unanswered', 'failed']))<form method="POST" action="{{ route('admin.business-profile.reviews.draft', [$website, $review]) }}" class="mt-3">@csrf<button class="rounded-md border px-3 py-2 text-xs font-medium">Generate reply draft</button></form>@else<p class="mt-2 text-xs capitalize text-slate-500">{{ str_replace('_', ' ', $review->reply_status) }}</p>@endif</article>@empty<p class="text-sm text-slate-500">No reviews synced yet.</p>@endforelse</div></section>
        </div>

        <section class="rounded-lg border border-slate-200 bg-white p-4"><h3 class="font-semibold text-slate-950">Automation settings</h3><form method="POST" action="{{ route('admin.business-profile.update', $website) }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf @method('PUT')<label class="flex items-center gap-2"><input type="hidden" name="weekly_audits_enabled" value="0"><input type="checkbox" name="weekly_audits_enabled" value="1" @checked($profile->weekly_audits_enabled)><span class="text-sm">Run weekly health checks</span></label><label class="flex items-center gap-2"><input type="hidden" name="weekly_posts_enabled" value="0"><input type="checkbox" name="weekly_posts_enabled" value="1" @checked($profile->weekly_posts_enabled)><span class="text-sm">Generate one post draft weekly</span></label><select name="post_weekday" class="rounded-md border px-3 py-2 text-sm">@foreach (['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as $value => $day)<option value="{{ $value }}" @selected($profile->post_weekday === $value)>{{ $day }}</option>@endforeach</select><select name="post_hour" class="rounded-md border px-3 py-2 text-sm">@for ($hour=0;$hour<24;$hour++)<option value="{{ $hour }}" @selected($profile->post_hour === $hour)>{{ str_pad($hour, 2, '0', STR_PAD_LEFT) }}:00</option>@endfor</select><input name="timezone" value="{{ $profile->timezone }}" class="rounded-md border px-3 py-2 text-sm"><textarea name="brand_guidance" rows="5" maxlength="20000" class="rounded-md border px-3 py-2 text-sm" placeholder="Tone, claims, and topics to avoid">{{ $profile->brand_guidance }}</textarea><button class="w-fit rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white">Save settings</button></form></section>
        @endif
    @endif
</div>
