@php
    $selectedPage = $pageWorkspace['selected'];
    $pages = $pageWorkspace['pages'];
@endphp
<section class="space-y-6" aria-labelledby="page-workspace-title">
    <header><h2 id="page-workspace-title" class="text-xl font-semibold">{{ $selectedPage ? 'Page workspace' : 'Your pages' }}</h2><p class="mt-2 text-base text-slate-600 sm:text-sm">A shared view of each page’s audit findings, search evidence, queued work and measured changes.</p></header>
    @if ($selectedPage)
        <div class="flex flex-wrap items-start justify-between gap-4"><p class="min-w-0 break-all font-medium">{{ $selectedPage['url'] }}</p><a class="ui-button ui-button-secondary" href="{{ route('admin.websites.section', [$website, 'seo', 'seo_section' => 'pages']) }}">All pages</a></div>
        <section class="ui-panel ui-section"><h3 class="font-semibold">Audit findings</h3><p class="mt-2 text-base text-slate-500 sm:text-sm">{{ $selectedPage['audit'] ? 'Last audit: '.$selectedPage['audited_at']?->format('j M Y') : 'This page has not been included in a completed audit yet.' }}</p><div class="mt-4 divide-y divide-slate-950/10">@foreach ($selectedPage['audit']?->checks ?? [] as $check)<div class="flex gap-4 py-3"><p class="shrink-0 text-sm font-medium {{ $check['status'] === 'passed' ? 'text-teal-700' : 'text-amber-800' }}">{{ ucfirst($check['status']) }}</p><div><h4 class="font-medium">{{ $check['label'] }}</h4><p class="mt-1 text-base text-slate-600 sm:text-sm">{{ $check['message'] }}</p></div></div>@endforeach</div></section>
        <section class="ui-panel ui-section"><h3 class="font-semibold">Search evidence</h3><p class="mt-2 text-base text-slate-500 sm:text-sm">Search Console opportunities are saved query/page samples, not total traffic for this page. Exact tracked ranks below are separate third-party observations.</p>
            <div class="mt-4 max-h-80 space-y-3 overflow-y-auto overscroll-contain">@forelse ($selectedPage['search_signals'] as $signal)<div class="ui-well p-4"><h4 class="font-medium">{{ $signal->query }}</h4><p class="mt-1 text-base text-slate-600 sm:text-sm">{{ $signal->summary }}</p><p class="mt-2 text-sm text-slate-500">{{ $signal->last_detected_at?->format('j M Y') }} · Search Console</p></div>@empty<p class="text-base text-slate-500 sm:text-sm">No saved Search Console opportunity sample for this page yet.</p>@endforelse</div>
            <div class="mt-4 max-h-80 space-y-3 overflow-y-auto overscroll-contain">@foreach ($selectedPage['rankings'] as $ranking)<p class="text-base text-slate-600 sm:text-sm">{{ $ranking->targetKeyword?->term }} · {{ $ranking->position ? '#'.$ranking->position : str($ranking->status)->replace('_', ' ') }} · {{ $ranking->device }} · {{ $ranking->language_code }} · Market {{ $ranking->location_code }} · {{ $ranking->observed_at?->format('j M Y') }}</p>@endforeach</div>
        </section>
        <section class="ui-panel ui-section"><div class="flex flex-wrap justify-between gap-3"><h3 class="font-semibold">Recommended work</h3><a class="ui-button ui-button-secondary ui-button-small" href="{{ route('admin.websites.section', [$website, 'seo', 'seo_section' => 'actions']) }}">Open action list</a></div>@forelse ($selectedPage['actions'] as $action)<p class="mt-3 text-base text-slate-600 sm:text-sm">{{ ucfirst($action['stage']) }} · {{ $action['reason'] }}</p>@empty<p class="mt-3 text-base text-slate-500 sm:text-sm">No outstanding recommendation for this page.</p>@endforelse</section>
        <section class="ui-panel ui-section"><h3 class="font-semibold">Changes and results</h3><div class="mt-4 max-h-96 space-y-4 overflow-y-auto overscroll-contain">@forelse ($selectedPage['impacts'] as $impact)<article class="ui-well p-4"><h4 class="font-medium"><a class="text-teal-700 underline" href="{{ route('admin.websites.section', [$website, 'seo', 'seo_section' => 'impact', 'seo_impact' => $impact->id]) }}">{{ $impact->title }}</a></h4><p class="mt-2 text-base text-slate-600 sm:text-sm">{{ ucfirst(str_replace('_', ' ', $impact->status)) }} · {{ $impact->live_at?->format('j M Y') ?: 'Awaiting delivery' }}</p><p class="mt-2 text-base text-slate-600 sm:text-sm">{{ $impact->automatic_summary ?: $impact->hypothesis }}</p></article>@empty<p class="text-base text-slate-500 sm:text-sm">Tracked changes and their results will appear here automatically.</p>@endforelse</div></section>
    @else
        @php
            $pageNumber = max(1, request()->integer('pages_page', 1));
            $pageList = new \Illuminate\Pagination\LengthAwarePaginator($pages->forPage($pageNumber, 25)->values(), $pages->count(), 25, $pageNumber, ['path' => request()->url(), 'pageName' => 'pages_page', 'query' => request()->except('pages_page')]);
        @endphp
        <div class="divide-y divide-slate-950/10">@forelse ($pageList as $page)<article class="flex flex-wrap items-center justify-between gap-4 py-4"><div class="min-w-0"><h3 class="break-all font-medium">{{ $page['audit']?->title ?: $page['url'] }}</h3><p class="mt-1 break-all text-base text-slate-500 sm:text-sm">{{ $page['url'] }}</p><p class="mt-2 text-sm text-slate-600">{{ $page['actions']->count() }} action groups · {{ $page['impacts']->count() }} tracked changes</p></div><a class="ui-button ui-button-secondary" href="{{ route('admin.websites.section', [$website, 'seo', 'seo_section' => 'pages', 'page_url' => $page['url']]) }}">Open page</a></article>@empty<div class="ui-well p-6"><p>No known pages yet. Run a site audit or connect your search data to begin.</p></div>@endforelse</div>
        {{ $pageList->links() }}
    @endif
</section>
