        <section class="ui-panel ui-section" aria-labelledby="impact-brief">
            <h2 id="impact-brief" class="font-semibold text-slate-950">1. Measurable brief</h2>
            <p class="mt-2 text-slate-600 text-base sm:text-sm">Define the pages, search intent, and expected effect before publishing. The measurement scope is frozen when delivery is confirmed.</p>
            @if ($canManage && ($seoImpact->status === 'planned' || $seoImpact->verification_status === 'scope_missing'))
                <form method="POST" action="{{ route('admin.seo-impacts.update', [$website, $seoImpact]) }}" class="mt-4 grid gap-4 md:grid-cols-2">
                    @csrf @method('PUT')
                    <div class="md:col-span-2"><label for="title" class="ui-label block">Objective</label><input id="title" name="title" required maxlength="200" value="{{ old('title', $seoImpact->title) }}" class="ui-input mt-1 w-full"></div>
                    <div class="md:col-span-2"><label for="hypothesis" class="ui-label block">What will change, and why should it help?</label><textarea id="hypothesis" name="hypothesis" required maxlength="2000" rows="3" class="ui-input mt-1 w-full">{{ old('hypothesis', $seoImpact->hypothesis) }}</textarea></div>
                    <div><label for="target_urls" class="ui-label block">Canonical target URLs · one per line, up to five</label><textarea id="target_urls" name="target_urls" required rows="4" class="ui-input mt-1 w-full">{{ is_array(old('target_urls')) ? implode("\n", old('target_urls')) : old('target_urls', implode("\n", $seoImpact->target_urls)) }}</textarea></div>
                    <div><label for="target_queries" class="ui-label block">Exact search terms · one per line, up to ten</label><textarea id="target_queries" name="target_queries" rows="4" class="ui-input mt-1 w-full">{{ is_array(old('target_queries')) ? implode("\n", old('target_queries')) : old('target_queries', implode("\n", $seoImpact->target_queries)) }}</textarea><p class="mt-1 text-slate-500 text-base sm:text-sm">Leave empty for all searches to these pages. Choose non-branded terms to measure discovery separately.</p></div>
                    <div><label for="primary_metric" class="ui-label block">Primary success measure</label><select id="primary_metric" name="primary_metric" class="ui-input mt-1 w-full"><option value="clicks" @selected(old('primary_metric', $seoImpact->primary_metric) === 'clicks')>Relevant search clicks</option><option value="ctr" @selected(old('primary_metric', $seoImpact->primary_metric) === 'ctr')>Search click-through rate</option></select></div>
                    <div><label for="control_url" class="ui-label block">Unchanged comparison page (optional)</label><input type="url" id="control_url" name="control_url" value="{{ old('control_url', $seoImpact->control_url) }}" class="ui-input mt-1 w-full"><p class="mt-1 text-slate-500 text-base sm:text-sm">Choose a similar page with similar demand. Comparison uses all of its queries.</p></div>
                    <div><label for="country" class="ui-label block">Country (optional, three-letter code)</label><input id="country" name="country" maxlength="3" placeholder="gbr" value="{{ old('country', $seoImpact->country) }}" class="ui-input mt-1 w-full"></div>
                    <div><label for="device" class="ui-label block">Device</label><select id="device" name="device" class="ui-input mt-1 w-full"><option value="">All devices</option>@foreach (['DESKTOP', 'MOBILE', 'TABLET'] as $device)<option value="{{ $device }}" @selected(old('device', $seoImpact->device) === $device)>{{ ucfirst(strtolower($device)) }}</option>@endforeach</select></div>
                    @foreach (['business_value' => 'Business value', 'confidence' => 'Evidence confidence', 'effort' => 'Implementation effort'] as $field => $label)
                        <div><label for="{{ $field }}" class="ui-label block">{{ $label }}</label><select id="{{ $field }}" name="{{ $field }}" class="ui-input mt-1 w-full">@for ($score = 1; $score <= 5; $score++)<option value="{{ $score }}" @selected((int) old($field, $seoImpact->$field) === $score)>{{ $score }}{{ $score === 1 ? ' · Low' : ($score === 5 ? ' · High' : '') }}</option>@endfor</select></div>
                    @endforeach
                    <div class="md:col-span-2"><button type="submit" class="ui-button ui-button-primary">Save brief</button></div>
                </form>
            @else
                <p class="mt-4 whitespace-pre-line text-slate-700 text-base sm:text-sm">{{ $seoImpact->hypothesis }}</p>
                <dl class="mt-4 space-y-3 text-sm"><div><dt class="font-medium">Target pages</dt><dd class="break-words text-slate-600">{{ implode(', ', $seoImpact->target_urls) ?: 'Not yet specified' }}</dd></div><div><dt class="font-medium">Search terms</dt><dd class="text-slate-600">{{ implode(', ', $seoImpact->target_queries) ?: 'All queries to the target pages' }}</dd></div><div><dt class="font-medium">Success measure</dt><dd class="text-slate-600">{{ strtoupper($seoImpact->primary_metric) }} · {{ $seoImpact->country ?: 'All countries' }} · {{ $seoImpact->device ?: 'All devices' }}</dd></div></dl>
            @endif
            @if ($seoImpact->evidence)
                <details class="mt-4 border-t border-slate-100 pt-4"><summary class="cursor-pointer text-sm font-medium text-slate-700">Original recommendation evidence</summary><pre class="mt-3 overflow-x-auto whitespace-pre-wrap break-words text-xs leading-5 text-slate-600">{{ json_encode($seoImpact->evidence, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre></details>
            @endif
        </section>
