@extends('layouts.app')

@section('content')
<div class="mx-auto max-w-4xl space-y-6">
    <div><p class="text-sm font-medium text-teal-700">Prospecting strategy</p><h1 class="text-3xl font-semibold tracking-tight">{{ $profile->exists ? 'Edit industry' : 'Add industry' }}</h1></div>
    <form method="POST" action="{{ $profile->exists ? route('admin.prospecting-industry-profiles.update', $profile) : route('admin.prospecting-industry-profiles.store') }}" class="grid gap-5 rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
        @csrf @if ($profile->exists) @method('PUT') @endif
        <div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium">Industry<input name="name" value="{{ old('name', $profile->name) }}" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label><label class="grid gap-1.5 text-sm font-medium">Slug<input name="slug" value="{{ old('slug', $profile->slug) }}" class="rounded-lg border border-slate-300 px-3 py-2.5"></label></div>
        <div class="grid gap-4 sm:grid-cols-3"><label class="grid gap-1.5 text-sm font-medium">Priority<input type="number" name="priority" value="{{ old('priority', $profile->priority ?? 50) }}" min="0" max="1000" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label><label class="grid gap-1.5 text-sm font-medium">Estimated customer value (£)<input type="number" name="estimated_customer_value" value="{{ old('estimated_customer_value', $profile->estimated_customer_value ?? 5000) }}" min="0" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label><label class="grid gap-1.5 text-sm font-medium">Value band<select name="customer_value_band" class="rounded-lg border border-slate-300 px-3 py-2.5">@foreach (['very_high' => 'Very high', 'high' => 'High', 'medium' => 'Medium', 'low' => 'Low'] as $value => $label)<option value="{{ $value }}" @selected(old('customer_value_band', $profile->customer_value_band ?? 'high') === $value)>{{ $label }}</option>@endforeach</select></label></div>
        <div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-sm font-medium">Service keywords<textarea name="service_keywords" rows="8" required class="rounded-lg border border-slate-300 px-3 py-2.5">{{ is_array(old('service_keywords')) ? implode("\n", old('service_keywords')) : old('service_keywords', implode("\n", $profile->service_keywords ?? [])) }}</textarea></label><label class="grid gap-1.5 text-sm font-medium">Priority search keywords<textarea name="search_keywords" rows="8" required class="rounded-lg border border-slate-300 px-3 py-2.5">{{ is_array(old('search_keywords')) ? implode("\n", old('search_keywords')) : old('search_keywords', implode("\n", $profile->search_keywords ?? [])) }}</textarea><span class="text-xs font-normal text-slate-500">The automatic command uses up to three strong searches per industry/location run.</span></label></div>
        <div class="grid gap-4 sm:grid-cols-4"><label class="grid gap-1.5 text-sm font-medium">Minimum position<input type="number" name="minimum_position" value="{{ old('minimum_position', $profile->minimum_position ?? 8) }}" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label><label class="grid gap-1.5 text-sm font-medium">Maximum position<input type="number" name="maximum_position" value="{{ old('maximum_position', $profile->maximum_position ?? 50) }}" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label><label class="grid gap-1.5 text-sm font-medium">Maximum pages<input type="number" name="maximum_site_size" value="{{ old('maximum_site_size', $profile->maximum_site_size ?? 30) }}" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label><label class="grid gap-1.5 text-sm font-medium">Import score<input type="number" name="automatic_import_score" value="{{ old('automatic_import_score', $profile->automatic_import_score ?? 65) }}" min="0" max="100" required class="rounded-lg border border-slate-300 px-3 py-2.5"></label></div>
        <label class="grid gap-1.5 text-sm font-medium">Notes / rationale<textarea name="notes" rows="4" class="rounded-lg border border-slate-300 px-3 py-2.5">{{ old('notes', $profile->notes) }}</textarea></label>
        <label class="flex items-center gap-3 text-sm font-medium"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $profile->exists ? $profile->enabled : true)) class="rounded border-slate-300">Enabled for automatic prospecting</label>
        @if ($errors->any())<div class="text-sm text-rose-700">{{ $errors->first() }}</div>@endif
        <div class="flex gap-3"><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save industry</button><a href="{{ route('admin.prospecting-industry-profiles.index') }}" class="px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</a></div>
    </form>
</div>
@endsection
